src/cppcache/integration-test/CacheHelper.cpp
src/cryptoimpl/SSLImpl.cpp

- Init SSLv23_client mode to support negotiation of all SSL/TLS
versions.
- Cleanup C++ style issues.
- Update tests to use NON-NULL cipher.

GEODE-2486: Initialize OpenSSL for DEFAULT cipher support.

---

docs/geode-native-book/master_middleman/source/subnavs/geode-nc-nav.erb
docs/geode-native-docs/gfcpp.properties/chapter_overview.html.md.erb
docs/geode-native-docs/gfcpp.properties/gfcpp.properties_search_path.html.md.erb
docs/geode-native-docs/setting-properties/attribute-def-priority.html.md.erb
docs/geode-native-docs/setting-properties/attributes-gfcpp.html.md.erb
docs/geode-native-docs/setting-properties/cache-server-config.html.md.erb
docs/geode-native-docs/setting-properties/chapter-overview.html.md.erb
docs/geode-native-docs/setting-properties/config-overview.html.md.erb
docs/geode-native-docs/setting-properties/native-client-config.html.md.erb

of Geode Native documentation
- Removed references to Pivotal GemFire and related commercial products
- Changed 'native client' to 'client.'
- Cosmetic wording changes
@davebarnes97 @joeymcallister @echobravopapa @PivotalSarge @dgkimura @mmartell    Can you please review these changes?

GEODE-2513 Rebrand Setting System Properties section

---

docs/geode-native-docs/type_mappings/chapter_overview.html.md.erb
docs/geode-native-docs/type_mappings/cpp-class-to-dotnet-class-mappings.html.md.erb
docs/geode-native-docs/type_mappings/java-to-dotnet-type-mapping.html.md.erb

- section title is Interoperability of Language Classes and Types
- corrected namespaces (packages)
- removed duplicate table captions
@davebarnes97 @joeymcallister @dgkimura @mmartell @echobravopapa @PivotalSarge Can you please review these (mostly namespace) changes in the docs?

GEODE-2513 Unbrand docs section Interoperability

---

src/dependencies/ACE/CMakeLists.txt
src/dependencies/openssl/CMakeLists.txt

- This avoids trying to apply patches on Windows which can break if the source
wasn't actually checked out by a Windows git.

GEODE-2766: Only apply patches on Solaris

---

CONTRIBUTING.md

Fixing typo in client CONTRIBUTING.md file CMake 4.3 changed to be CMake 3.4. There is no version 4.3 of CMake.

GEODE-2780: Fixing typo in client CONTRIBUTING.md file

---

docs/geode-native-docs/introduction/client-configurations.html.md.erb
docs/geode-native-docs/introduction/quickstart.html.md.erb
docs/geode-native-docs/security/sslclientserver.html.md.erb

@pivotal-jbarrett @joeymcallister @davebarnes97 
Please review.  I have reduced the locations which call out which version of OpenSSL to use, and reworded to specify version 1.0.2 (no references to 'or a later version').  I also eliminated instructions for installing OpenSSL; they provide those, and we should not.

GEODE-3135 Update Geode Client docs OpenSSL version

---

CMakeLists.txt

Fixes Solaris SPARC linking error. For more information: https://docs.oracle.com/cd/E60778_01/html/E60746/gqhbq.html
Testing: built on solaris sparc

GEODE-3457: Linking fails on Solaris SPARC due to -xatomic=none option

---

cppcache/test/ClientProxyMembershipIDFactoryTest.cpp

Unittest passed on Mac and Solaris SPARC

GEODE-3497: Fix failing test on Solaris SPARC

---

cppcache/src/CacheFactory.cpp
cppcache/src/CppCacheLibrary.cpp
cppcache/src/CppCacheLibrary.hpp
cppcache/src/Log.cpp

Issue is that ACE_Singleton::instance call causes SEGV with xcode 8.3.3 developer toolset.  This change removes the offending usage of ACE_Singleton.
Testing: unit tests and integration tests passed

GEODE-2733: Fix integration test errors on xcode 8.3.3

---

dependencies/ACE/CMakeLists.txt

Integrations and unit tests pass using the updated version of ACE.

GEODE-3442: Upgrade ACE to 6.4.4

---

tests/cli/DUnitFramework/IClientServerComm.cs
tests/cli/DUnitFramework/UnitProcess.cs
tests/cli/FwkClient/ClientProcess.cs
tests/cli/FwkLauncher/LauncherProcess.cs

- Removes named pipe IPC channel.

GEODE-3558: Use TCP IPC channel only.

---

CMakeLists.txt

- Need to include -Thost=x64 in the configuration step

GEODE-2741: Adding a warning for 64bit Windows Tools sets

---

dependencies/boost/CMakeLists.txt

Upgrade to boost 65 to leverage additional modules, specifically boost::stacktrace

GEODE-3611: Upgrade boost dependency to version 1.65

---

clicache/integration-test/test.bat.in

Flaky test ThinClientPoolTestsN sometimes leaves lingering java processes (server/locator). If we cleanup after the test then the thought is that we can do a clean retry.

GEODE-3832: Add cleanup to .NET tests

---

cppcache/include/geode/DataOutput.hpp
cppcache/src/TcrMessage.cpp
cppcache/test/DataOutputTest.cpp

Testing: Unittests in TcrMessage that exercise this code all passed

GEODE-3728: Move DataOutput::writeFullUTF to TcrMessage

---

clicache/integration-test/CacheHelperN.cs
clicache/integration-test/ThinClientFunctionExecutionTestsN.cs
clicache/src/Cache.cpp
clicache/src/CacheFactory.cpp
clicache/src/DistributedSystem.cpp
clicache/src/DistributedSystem.hpp
cppcache/src/Cache.cpp
cppcache/src/CacheFactory.cpp
cppcache/src/DistributedSystem.cpp
cppcache/src/DistributedSystemImpl.cpp
cppcache/src/DistributedSystemImpl.hpp
cppcache/src/MapEntry.cpp
cppcache/src/MapEntry.hpp
cppcache/src/RegionFactory.cpp
cppcache/src/statistics/HostStatHelper.cpp

There are a couple of seemingly unrelated issues here but they relate. The unused code was just unused code and cleaning up make sense. The static lock around DS was left over form the app domain refcounting and since this test was creating and destroying lots of caches it made sense to eliminate it as a cause. Ultimately it came down to this test being long running and the windows stats collector being very buggy. Eventually the stats collector would cause a segfault and the test would either hang or fail.

 GEODE-4071: Stabilizes CLI integration tests, ThinClientFunctionExecutionTestsN

---

clicache/integration-test/ThinClientCSTXN.cs
clicache/src/Cache.cpp
clicache/src/CacheTransactionManager.cpp
clicache/src/CacheTransactionManager.hpp
clicache/src/TransactionId.hpp
cppcache/include/geode/CacheTransactionManager.hpp
cppcache/integration-test/CMakeLists.txt
cppcache/integration-test/ThinClientTransactions.hpp
cppcache/integration-test/ThinClientTransactionsXA.hpp
cppcache/integration-test/testThinClientTransactionsXA.cpp
cppcache/src/CacheTransactionManagerImpl.cpp
cppcache/src/CacheTransactionManagerImpl.hpp
cppcache/src/InternalCacheTransactionManager2PCImpl.cpp
cppcache/src/SuspendedTxExpiryHandler.cpp
cppcache/src/SuspendedTxExpiryHandler.hpp
cppcache/src/TXCleaner.cpp
cppcache/src/TXId.cpp
cppcache/src/TXId.hpp
cppcache/src/TXState.cpp
cppcache/src/TXState.hpp
cppcache/src/TcrMessage.cpp

Updates _CacheTransactionManager.hpp_ to use type ```TransactionId&``` instead of ```std::shared_ptr<TransactionId>```.
Notes: Important to note this change to ref forces behavior change because previous code returned nullptr when suspending transaction if transaction isn't currently in flight ([example](https://github.com/apache/geode-native/compare/develop...dgkimura:feature/GEODE-3391-transactionidref?expand=1#diff-1d700ac09f0ace4175f618859ead7f34L329)).  Now we instead throw.  If we wanted to preserve previous behavior, we would likely need to use raw/smart pointers instead of references.
Testing: All stable integration tests and unittests passed on Mac and Windows.  Note that all but 1 of transaction tests are currently marked flaky...  I will try to tackle fixing these tests in …

GEODE-3391: Update Transaction id to pass by references

---

cppcache/include/geode/PdxSerializable.hpp
cppcache/include/geode/Serializable.hpp
cppcache/integration-test/DeltaEx.hpp
cppcache/src/PdxHelper.cpp
cppcache/src/PdxHelper.hpp
cppcache/src/PdxType.hpp
tests/cpp/testobject/DeltaPSTObject.hpp

- Adds std::enable_shared_from_this to PdxSerializable to satisfy some
strange serialization behavior. See GEODE-4359

GEODE-4314: Removes std::enable_shared_from_this.

---

clicache/src/PoolFactory.hpp
cppcache/include/geode/PoolFactory.hpp
cppcache/include/geode/RegionAttributes.hpp
cppcache/src/CacheTransactionManagerImpl.cpp
cppcache/src/EntriesMapFactory.cpp
cppcache/src/EntryExpiryHandler.cpp
cppcache/src/LocalRegion.cpp
cppcache/src/PoolFactory.cpp
cppcache/src/SystemProperties.cpp
cppcache/src/TcrConnection.cpp
cppcache/src/ThinClientPoolDM.cpp
cppcache/src/TombstoneList.cpp
cppcache/src/statistics/PoolStatsSampler.cpp
cppcache/src/statistics/PoolStatsSampler.hpp

- Durations that can be disabled use std::chrono::duration::zero().
- Fixes durations that are out of range based on documention.
- Fixes comparison of durations against limits or disabled.
- Updates documentation for changes to duration values.
- Fixes exception throw for invalid arguments.

 GEODE-3570: Standardizes time values.

---

cppcache/include/geode/PdxFieldTypes.hpp
cppcache/include/geode/PdxInstance.hpp
cppcache/src/PdxFieldType.cpp
cppcache/src/PdxFieldType.hpp
cppcache/src/PdxInstanceImpl.cpp
cppcache/src/PdxInstanceImpl.hpp
cppcache/src/PdxLocalReader.cpp
cppcache/src/PdxLocalReader.hpp
cppcache/src/PdxReaderWithTypeCollector.cpp
cppcache/src/PdxReaderWithTypeCollector.hpp
cppcache/src/PdxRemoteReader.cpp
cppcache/src/PdxRemoteReader.hpp
cppcache/src/PdxType.cpp
cppcache/src/PdxType.hpp

- Removes unused readCollection, which had an undefined PDX field type.

GEODE-4426: Refactor PdxFieldTypes as enum class.

---

cppcache/include/geode/CacheableKey.hpp
cppcache/include/geode/Properties.hpp
cppcache/src/Properties.cpp

You should notice that I dropped the half implemented thread safety in this class. Properties are never kept or shared between threads. I believe the original was made, incompletely, thread safe to mimic Java Properties class, which is fully synchronized.

GEODE-4425: Replaces ACE map with std::unordered_map.

---

packer/rhel/install-build-rpms.sh

Cause apparently RHEL7 base image no longer has patch

GEODE-4899: Add missing patch to RHEL7

---

cppcache/integration-test/testXmlCacheCreationWithPools.cpp
cryptoimpl/DHImpl.cpp
dhimpl/DHImpl.cpp
tests/cpp/testobject/BatchObject.hpp
tests/cpp/testobject/DeltaFastAssetAccount.hpp
tests/cpp/testobject/DeltaPSTObject.hpp
tests/cpp/testobject/EqStruct.hpp
tests/cpp/testobject/PSTObject.hpp

- Missing inttypes.h header added
- Remaining references to 'ret' in log messages removed

GEODE-4994: Fix windows compilation

---

defaultSystem/geode.properties

@davebarnes97 and I stumbled upon these when looking at some documentation

 GEODE-4728 - Update defaultSystem/geode.properties

---

packer/windows/install-chocolatey.ps1

https://github.com/chocolatey/choco/issues/1529 has been resolved and chocolatey 0.10.10 does not have the issue when running packer now

GEODE-4956: revert to latest chocolatey

---

clicache/integration-test/TestCacheXmlInitializationN.cs
clicache/integration-test/ThinClientAppDomainFunctionExecutionTests.cs
clicache/src/native_conditional_shared_ptr.hpp
clicache/test/AssemblyInfo.cpp.in
clicache/test/Utils.hpp
cmake/PrecompiledHeader.cmake
packer/windows/vs-2015-admin.xml

Several files were missing licenses, I added them except for solaris.patch because I do not know how to add comments to a patch file

GEODE-5191: Add missing license

---

cppcache/integration-test/testPdxMetadataCheckTest.cpp

Integration test would not build with clang.
- removed unused macro
- added newline at eof

GEODE-5289: Fix build issue for testPdxMetadataCheckTest 

---

packer/windows/install-ssh.ps1

Moving to latest version for Windows, to see if that helps some of the instability.
Co-authored-by: Mike Martell <mmartell@pivotal.io>

Remove version specifier from install-ssh

---

packer/windows/install-dependencies.ps1

broke references in our .net projects
Co-authored-by: Jacob Barrett <jbarrett@pivotal.io>

Fix cmake version at 3.11.4 for now, til we can figure out how 3.12

---

cppcache/include/geode/CacheStatistics.hpp
cppcache/src/CacheStatistics.cpp
cppcache/src/MapEntry.hpp

…rono::time_point ctors
Co-authored-by: Ivan Godwin <igodwin@pivotal.io>

GEODE-5567:  Replace template parameter of std::atomic with a known trivially-copyable type

---

clicache/src/CacheFactory.hpp

Changes touch only 2 comment lines to correct auto-generated API docs.
No code was harmed in the making of this PR

GEODE-5582: Fix .NET API docs errors (CacheFactory.hpp)

---

.cpackignore
CMakeLists.txt

See notes in JIRA for full details.  tl;dr version: Geode includes their Docker/Packer files, so we will too, and the one-line change to CMakeLists.txt is (probably) the last thing we need for cpack.

Geode-2607: improve release artifacts

---

cppcache/src/statistics/StatArchiveWriter.cpp
cppcache/src/statistics/StatArchiveWriter.hpp

When the simple example code listed in GEODE-5713 was run under Valgrind on Linux, it generated a complaint about use of an uninitialized variable in a loop in the statistics code.  This _appears_ to have been a red herring, since as far as we can tell the value in question was definitely initialized, but... cleaning things up a bit without changing semantics seems to get rid of the error message.
- replaced use of member var `numOfDescps` with a local var initialized from the contained type object
- removed (no longer used) member var `numOfDescps`
- removed gratuitous use of `this` pointer

GEODE-5713: fix valgrind uninitialized value

---

cppcache/integration-test-2/CMakeLists.txt
cppcache/integration-test-2/RegisterKeysTest.cpp
cppcache/integration-test-2/framework/Cluster.h
cppcache/integration-test-2/framework/GfshExecute.cpp
cppcache/integration-test-2/framework/GfshExecute.h
cppcache/src/ThinClientRegion.cpp

- Refactor Cluster class so we can apply locators separately.
- Clean up server directories at test startup.
- Add test cases for caching proxy and proxy regions with getInitialValues set to true
- remove extraneous comment and empty doc comments
- throw exception if gfsh exits non-zero
- use relative path when deleting server directory

GEODE-5626: Fix crash in register all keys

---

.clang-format
cppcache/integration-test/testThinClientCq.cpp
cppcache/src/SerializableHelper.hpp

- Remove problematic clang-format options
- Anonymize unused parameters
- Remove unnecessary type cast

GEODE-5259: Fix clang (xcode 10) build breaks

---

CMakeLists.txt
clicache/src/CacheableBuiltins.hpp
cppcache/include/geode/CacheableBuiltins.hpp
cppcache/include/geode/internal/CacheableBuiltinTemplates.hpp
cppcache/integration-test/testThinClientSecurityAuthorizationMU.cpp
cppcache/src/PdxInstanceFactory.cpp
cppcache/src/PdxInstanceImpl.cpp
cppcache/src/SerializationRegistry.hpp

Replaces the old macros with templates to define `Cacheable` built in types. This allows you to debug into the types should there be issues.

GEODE-5025: Uses templates to define Cacheable types

---

cppcache/integration-test/CMakeLists.txt

This change puts all of the old framework cpp integration tests into a legacy subdirectory to make it easier to find the other test related projects.

GEODE-5638: Move cppcache/integration-tests to legacy

---

cppcache/include/geode/PersistenceManager.hpp
cppcache/integration-test/testOverflowPutGetSqLite.cpp
cppcache/src/PersistenceManager.cpp
sqliteimpl/SqLiteImpl.cpp

- These should just be agreed-upon values between client code and plugin
Co-authored-by: Sai Boorlagaddda <sai.boorlagadda@gmail.com>

GEODE-5942: Remove named constants from PersistenceManager

---

.lgtm.yml

Following our conversation [here](https://discuss.lgtm.com/t/apache-geode-native-not-detected-as-c-project/1506/13) about getting the C++ code building on LGTM.com, here's the configuration file that was used.
By including it here, you'll be able to update it when a different version of geode is needed to successfully build the project, and add further configuration options etc.
cc @pivotal-jbarrett

Create configuration for LGTM.com

---

cmake/FindGeode.cmake

- Function execution example includes a jar, so we need Geode to build the java code
- Geode find module problem was breaking build of examples.  It was setting the 'hints' variable to the value of GEODE_ROOT, which only works if the 'paths' parameter to find_package_handle_standard_args is empty, but it was always setting paths.  Switched it to set one or the other like the FindGeodeNative find module does, and all is better.

GEODE-4337: Correct Path Searching in FindGeode module

---

docker/Dockerfile

- libc++api-dev (non-existent) changed to libc++abi-dev
Docker image successfully builds and geode-native is able to be built on resulting image.

GEODE-6012: Corrected package name in Dockerfile

---

BUILDING.md
CMakeLists.txt

This updates the cmake minimum version from 3.10 to 3.12.

GEODE-6022: Make 3.12 the minimum cmake version

---

packer/windows-2012-r2-base.json
packer/windows/install-dependencies.ps1
packer/windows/install-doxygen.ps1
packer/windows/uninstall-doxygen.ps1

- Actually invokes Chocolatey-InstallPackage Powershell module directly with the correct URL, rather than use the Doxygen install package
- Easily removed once Doxygen package is fixed
Co-authored-by: Ernest Burghardt <eburghardt@pivotal.io>

GEODe-6165: Bypass chocolately for install of Doxygen on Windows

---

cppcache/integration-test-2/FunctionExecutionTest.cpp
cppcache/src/ThinClientRegion.cpp

- Handle request data error messages for function execution on a region.
Signed-off-by: Ernest Burghardt <eburghardt@pivotal.io>

GEODE-5957: Parse (previously) unknown server error messages

---

.cpackignore

GEODE-6160: Properly escape backslashes in .cpackignore

---

examples/dotnet/CMakeLists.txt

- a .md file was deleted from the repo, but not removed from the install list

GEODE-6114: Fix cpack break in examples

---

packer/windows/install-doxygen.ps1
packer/windows/uninstall-doxygen.ps1

- Doxygen Powershell scripts were missing license headers

GEODE-6165: Fix rat errors

---

examples/cpp/CMakeLists.txt
examples/cpp/transaction/README.md
examples/cpp/transaction/main.cpp
examples/cpp/transaction/startserver.sh
examples/cpp/transaction/stopserver.sh

- demonstrates commit and rollback of transactions
- handles exceptions

GEODE-6210: Add 'transaction' example for cpp

---

cppcache/integration/test/RegionPutGetAllTest.cpp
cppcache/src/TcrMessage.cpp

This adds an error handler to TcrMessage to catch PUT_DATA_ERROR messages from the server. Also adds a test to ensure a proper exception is bubbled up to the user.

Geode-5962: Fix putAll crash with null values

---

cppcache/src/ThreadPool.cpp
cppcache/src/ThreadPool.hpp

Need to make sure *everything* run in thread pool gets the rightAppDomain context

GEODE-6300: Fix AddDomain gripe in CLI tests

---

examples/cpp/sslputget/CMakeLists.txt.in
examples/dotnet/sslputget/CMakeLists.txt.in

.net SSL example didn't parameterize things correctly in its CMakeLists.txt

GEODE-4339: fix build

---

cppcache/integration/test/CMakeLists.txt
cppcache/src/PutAllPartialResult.cpp
cppcache/src/ThinClientRegion.cpp
cppcache/src/VersionedCacheableObjectPartList.hpp

Use shared pointer directly instead of create a shared pointer from a raw pointer.

GEODE-5708: fix memory corruption.

---

cppcache/src/SerializationRegistry.cpp
cppcache/src/TcrConnection.cpp
cppcache/src/TcrConnection.hpp

If memberId length grew longer than 127 characters, which happens in some environments, geode-native would overflow a signed byte and start looking for a negative-length array.  Bad things happened after that.
Co-Authored-By: Mike Martell <mmartell@pivotal.io>
Co-Authored-By: Jacob Barrett <jbarrett@pivotal.io>

GEODE-6491: Fix signed/unsigned problem reading size field in handshake message

---

cppcache/src/ClientMetadataService.cpp
cppcache/src/ClientMetadataService.hpp

This fixes the occasional "can't pass GCHandle across AppDomains" exception caused by the ClientMetaDataService background thread.

GEODE-6597: Add appDomainContext to the ClientMetaDataService.

---

cppcache/src/TcrConnection.cpp
cppcache/src/TcrConnection.hpp
cppcache/src/TcrEndpoint.cpp
cppcache/src/TcrEndpoint.hpp
cppcache/src/TcrPoolEndPoint.cpp
cppcache/src/TcrPoolEndPoint.hpp

The method in TcrConnection greatly needed clarification/simplification, and the corresponding methods in Tcr*Endpoint literally do nothing.  This is a nice small thing that can be done to make things more readable and maintainable.

GEODE-6718: Refactor TcrConnection::sendRequestForChunkedResponse, derived class, and remove pass-through calls in TrcConnection and derived

---

cppcache/src/TcrChunkedContext.hpp
cppcache/src/TcrConnection.cpp
cppcache/src/TcrConnection.hpp
cppcache/src/TcrMessage.cpp
cppcache/src/TcrMessage.hpp
dependencies/rat/CMakeLists.txt

The purpose and functionality of TcrConnection::readMessageChunked should now be more apparent.  Refactored it into several helper methods, cleaned up named constants and variable names, de-obfuscated confusing loop logic.

GEODE-6826: Refactor chunk processing

---

clicache/src/IRegion.hpp
examples/dotnet/putgetremove/Program.cs

- Also remove unnecessary parameter to IRegion::Put call in PutGetRemove
.net example

GEODE-6546: Fix doc comments for IRegion

---

cppcache/include/geode/CacheableFileName.hpp

Having the ctors inline is throwing some versions of gcc and clang through a loop. Not having them in the vtable is tolerated by some, but causing linker errors on others.

GEODE-6800: CacheableFileName Linker Error

---

cppcache/src/TcrMessage.cpp

This was causing a negative test for Region::PutAll to fail, on one (and only one) of our test machines, the error message coming back from the server contains leading whitespace.  Simply trimming the leading space fixes the test failure.

GEODE-6961: Trim leading whitespace from server error message

---

cppcache/integration/test/FunctionExecutionTest.cpp

negative test case for values which can't be deserialized on server
- test wasn't connecting to locator properly, so it was getting the wrong exception
Co-authored-by: Mike Martell <mmartell@pivotal.io>
@steve-sienk, @mreddington

GEODE-7040: Fix function execution test

---

.travis.yml
docker/Dockerfile

- Apache Creadur Rat version upgraded to 0.13
- Docker image tag changed to apachegeode/geode-native-build:latest

GEODE-7147: Update Travis-CI resources

---

cppcache/src/TcpSslConn.cpp

This enables successful compilation with gcc 8.3

GEODE-7182: fix warning in TcpSslConn.cpp 

---

examples/cpp/pdxserializable/Order.cpp

- std::endl doesn't work in string concatenation expression
@mreddington @steve-sienk @vfordpivotal @charliemblack @dihardman

GEODE-7203: Fix build break in examples

---

CMakeLists.txt

- Got a new version of the compiler from Apple, this is breaking Mac builds

GEODE-7235: Disable a couple of new Clang warnings temporarily

---

.lgtm.yml

- 1.9.0 no longer exists so lgtm doesn't actually build.  Updated it for 1.10.0
@vfordpivotal @steve-sienk @mreddington

Update lgtm to point to current Geode (1.10.0)

---

CMakeLists.txt

-  One of the new flags added for Clang 11 support, -Wno-defaulted-function-deleted, was not available to earlier versions of Clang
Co-authored-by: Michael Oleske <moleske@pivotal.io>

GEODE-7235: Add backwards compatibility for Clang

---

packer/build-windows.json
packer/windows/install-activeperl.ps1

Co-authored-by: Blake Bender <bbender@pivotal.io>
Co-authored-by: Michael Oleske <moleske@pivotal.io>
Active perl is timing out on chocolatey installs, so install separately.
@steve-sienk @vfordpivotal @mreddington

GEODE-7429: Install Active Perl separately

---

BUILDING.md
CONTRIBUTING.md

I have experienced this issue with the `BasicIPv6Test` integration test, I think it should be documented.

Add note about BasicIPv6Test

---

cppcache/src/ClientMetadataService.cpp
cppcache/src/EntryExpiryHandler.cpp
cppcache/src/LocalRegion.cpp
cppcache/src/MapEntry.hpp
cppcache/src/RegionExpiryHandler.cpp
cppcache/src/TcpConn.cpp
cppcache/src/TcpSslConn.cpp
cppcache/src/TcrConnection.cpp
cppcache/src/TcrEndpoint.cpp
cppcache/src/ThinClientRegion.cpp

- std::chrono 'Rep' type changes size based on platform
- when size mismatched to format spec in log call, bad things happen

GEODE-7447: Fix logging format spec <--> variable size mismatches

---

cryptoimpl/SSLImpl.cpp

When using TLS, geode native client throws an exception due to wrong order on method calling:
"Exception while querying locator: apache::geode::client::SslException: Invalid SSL keystore password."
This is due to in SSLImpl.cpp constructor, the private key is added before the certificate. According to ACE documentation, we should reverse order due to when the private key is added it is verified against the certificate. So we should call sslctx->private_key after calling sslctx->certificate
http://www.aoc.nrao.edu/php/tjuerges/ALMA/ACE-5.8.1/html/ace/a00493.html#a5fa01171382ad69ac372dae7e3860211

GEODE-7451: Fix cert & priv key add order

---

BUILDING.md
cppcache/src/ThinClientStickyManager.cpp
cppcache/src/ThinClientStickyManager.hpp
dependencies/ACE/CMakeLists.txt

The only source code issue found with using Visual Studio 2019 was the removal of an unused function call which was declared NODISCARD. 
Also, the CMakeLists.txt for ACE needed to be told about the newer MSVC_VERSION.

GEODE-7490: Support Visual Studio 2019

---

cppcache/include/geode/internal/chrono/duration.hpp
cppcache/src/EntryExpiryHandler.cpp
cppcache/test/util/chrono/durationTest.cpp

- std::chrono for things like system time on Windows return a
non-standard ratio corresponding to 'ticks' (100ns units)
- This unit was blowing up our string conversion code, which defaulted
to nullptr for string value of unrecognized units
Fix is threefold, for redundancy:
- Normalize the units in the place where the tests were choking on it, since the base value was in seconds to begin with
- Don't return nullptr in the default case, to avoid the crash in other places we may have missed
- Add "ticks" units for Windows, which in obscure cases may help us distinguish between this specific problem and a units problem we may hit on another platform
@mreddington @dihardman @davebarnes97 @vfordpivotal

GEODE-7447: Fix test breakage on Windows

---

cppcache/src/ThinClientPoolDM.cpp

When using a connection pool, the server endpoint name string was being limited to 128 characters. This prevented using the native client with PCF 1.9.1 which switched from IP addresses to DNS names. These names can often be greater than 128 characters as in: 
05b92a19-be8e-4b55-8bd6-db83073a375b.locator-server.nassau-services-subnet.service-instance-c0abaded-6ac6-4f6f-80b2-a141d01ac3f8.bosh

GEODE-7511: Fix endpoint truncation bug

---

cppcache/integration/test/CqTest.cpp
cppcache/src/EntryExpiryHandler.cpp
cppcache/src/ExpiryTaskManager.cpp
cppcache/src/ExpiryTaskManager.hpp
cppcache/src/PdxInstanceImpl.cpp
cppcache/src/PreservedDataExpiryHandler.cpp
cppcache/src/RegionExpiryHandler.cpp
cppcache/src/TcrMessage.cpp
cppcache/src/ThinClientPoolDM.cpp
cppcache/src/TombstoneExpiryHandler.cpp
cppcache/src/statistics/AtomicStatisticsImpl.hpp
cppcache/src/statistics/StatArchiveWriter.hpp
tests/cpp/fwklib/UDPIpc.hpp
tests/cpp/testobject/NonPdxType.hpp
tests/cpp/testobject/PdxType.cpp

This commit solves some more memory leaks
and uninitialized memory accesses found
in the C++ client when running the integration
tests that were not solved by GEODE-7476

GEODE-7509: Fix memory leaks in C++ client

---

BUILDING.md
cmake/ClangFormat.cmake

- Will save time on developer builds
- Stops breaking Windows builds when Visual Studio clang-format crashes
@mreddington @vfordpivotal @dihardman @davebarnes97 @karensmolermiller

GEODE-7520: Add convenient target to clangformat everything

---

cppcache/src/Log.cpp

This code was supposed to disable debug level logging for non-debug builds. Apparently it never worked. I fixed it when I moved it to the source file, but it broke the tests. That means release could log debug. That means it's out in the wild. Instead of arbitrarily disabling a log level and possibly hampering a customer, we decided to disable this compile-time feature altogether.

GEODE-7612: Technical debt 01 - Fix logging

---

examples/cpp/sslputget/CMakeLists.txt.in
examples/cpp/sslputget/README.md

This removes the need to set LD_LIBRARY_PATH on Linux when running apps which are using SSL. Since OSX ignores LD_LIBRARY_PATH (unless SIP is disabled), this fix allows identical setup of SSL enabled native client apps on OSX and Linux.
Also updates the README.md for the sslputget example to remove the LD_LIBRARY_PATH requirement.

GEODE-7646: Remove need for LD_LIBRARY_PATH on Linux.

---

cppcache/integration/test/CMakeLists.txt
cppcache/integration/test/PdxJsonHandlerTest.cpp
cppcache/integration/test/PdxJsonTypeTest.cpp
cppcache/src/PdxType.cpp

The operator< method of PdxType in the native client simply compares the class names, which is incorrect and leads to the fact that, in NC, you cannot currently have two separate PDX types with the same class name. The comparison should favor type ID first, then if both type IDs are 0 (true for local regions), fall back to class name. This will still fail for local regions in the scenario where class names are the same, but it's much, much better than we have now.

GEODE-7694: fix pdx type lookup

---

cppcache/integration/test/SslOneWayTest.cpp
cppcache/integration/test/SslTwoWayTest.cpp

These snuck in with the addition of SslOneWayTest.cpp and SslTwoWayTest.cpp.  Most likely they were overlooked because they were new files rather than changes to existing ones, and because this was supposed to be just a “port” of the SSL test work done in a private branch.
@vfordpivotal @mreddington @dihardman @davebarnes97

GEODE-7785: Remove hard-coded path in (unused) global test variables

---

cppcache/integration/test/CMakeLists.txt
cppcache/integration/test/PdxJsonTypeTest.cpp
cppcache/src/PdxHelper.cpp
cppcache/src/PdxType.hpp

If deserialization in the PdxHelper fails, fall back to PdxInstance deserialization a la Jake.

GEODE-7794: Checking for null result and falling back to PdxInstance deserialization.

---

clicache/src/ISubscriptionService.hpp
cppcache/include/geode/Region.hpp

- setClientNotificationEnabled is a protected method on an internal class, not part of the public API
@mreddington @vfordpivotal @dihardman @davebarnes97 @karensmolermiller

GEODE-7887: Remove reference to nonexistent API from docs

---

cppcache/src/ThinClientPoolDM.cpp

- Removed truncation of endpoint when exceedes 99 chars
- Also, fixed wrong logging of error when endpoint is successfully
added to the pool
Related to solution, I haven't found any limitation checks e.g. if host name exceeds full domain maximum length (see JIRA for more info) in cases that work on native client (e.g. subscription is "disabled"), so I didn't put any restrictions of that kind in addEP function.
Related to integration test, I think that it would be hard to create generic tests to verify maximum supported length of host name name (see JIRA for more info), since host name depends on environment where the tests are executed. I only tested this manually.

GEODE-7930: Fix endpoint name truncation bug

---

cppcache/src/CacheImpl.cpp

While this was likely not a problem in C++ it was a big problem in .NET due to
the reliance on GC to destruct native objects. The StatsManager didn't stop
until it was destructed. This in turn stops the HostStatSampler. In .NET this
leaves the stats system trying to run on a closed but not destructed Cache
instance.

GEODE-8053: Fixes lingering StatsManager after Cache close.

---

clicache/integration-test/CMakeLists.txt
cppcache/integration-test/CMakeLists.txt

Use test DISABLED property to avoid accidental execution.

GEODE-8062: Disables flaky and omitted tests.

---

docker/Dockerfile

- Geode from 1.9 to 1.12
- CMake from 3.12.2 to 3.12.4
- Set to noninteractive so that building doesn't require interaction
- Make key=value for LABEL clearer
I'm not really sure how the Travis dockerfile has stayed up to date.  I'm assuming it is part of the release process to update it, but changes never get ported here since this was trying to install 1.9 which you can't download anymore.

GEODE-8183: Update dockerfile versions

---

clicache/integration-test/ExpirationTestsN.cs
cppcache/include/geode/SystemProperties.hpp
cppcache/integration-test/resources/system.properties
cppcache/integration-test/testExpiration.cpp
cppcache/integration-test/testSystemProperties.cpp
cppcache/src/LocalRegion.cpp
cppcache/src/SystemProperties.cpp
defaultSystem/geode.properties
docs/geode-native-docs-cpp/configuring/sysprops.html.md.erb

GEODE-8181: Fixes default value for statistic-sampling-enabled.

GEODE-8181: Fixes default value for statistic-sampling-enabled.

---

CMakeLists.txt
cppcache/integration/framework/GfshExecute.h
cppcache/src/TcrMessage.cpp
cryptoimpl/SSLImpl.hpp

I just used `__sun` and `_MSC_VER` as the check.  Worked for Windows, Mac, and Kubuntu 20.04.  Don't have a Sun based setup to test that one.  I checked the box for "Allow edits by maintainers" so just push up anything you might discover.

GEODE-8207: Enfore No Unknown Pragmas as Error

---

CMakeLists.txt
cppcache/src/ClientProxyMembershipIDFactory.cpp
cppcache/src/ClientProxyMembershipIDFactory.hpp
cppcache/src/PdxTypeRegistry.cpp
cppcache/src/PdxTypeRegistry.hpp
cppcache/src/statistics/StatArchiveWriter.cpp
cppcache/src/statistics/StatArchiveWriter.hpp
cppcache/test/ConnectionQueueTest.cpp

Seemed since we merged they enforce no shadow declarations might as well finish off the rest of shadow fields.  Also switched to `_` convention per style guide for member variables for files that needed fixed anyway

GEODE-8307: Enforce No Shadow Field in Constructor as Error

---

docs/geode-native-book-cpp/master_middleman/source/subnavs/geode-nc-nav.erb
docs/geode-native-book-dotnet/master_middleman/source/subnavs/geode-nc-nav.erb
docs/geode-native-docs-cpp/connection-pools/client-pool-api.html.md.erb
docs/geode-native-docs-cpp/connection-pools/running-connection-pool-code.html.md.erb
docs/geode-native-docs-dotnet/connection-pools/running-connection-pool-code.html.md.erb

Updated left-hand nav in both .NET and C++ guides to include "Using Connection Pools" and its subtopics
Made basic changes to text for language-specific books. Thorough update is the subject of another ticket.

GEODE-8390: Geode Native Client guide - expose "Connection Pools" in nav

---

CMakeLists.txt

curious if this is needed since quick test on my machine was compiling (so figured I'd make travis check real quick)
edit - will make a Jira when I bother to log into Jira next time

GEODE-8426: Enforce warning no-shorten-64-to-32

---

cppcache/integration/framework/Cluster.cpp
cppcache/integration/framework/Cluster.h
cppcache/integration/framework/Gfsh.cpp
cppcache/integration/framework/Gfsh.h
cppcache/integration/test/CMakeLists.txt
cppcache/integration/test/ExampleTest.cpp
cppcache/integration/test/Order.cpp
cppcache/integration/test/Order.hpp
cppcache/integration/test/WanDeserializationTest.cpp
cppcache/src/GatewaySenderEventCallbackArgument.cpp
cppcache/src/GatewaySenderEventCallbackArgument.hpp
cppcache/src/PdxInstanceImpl.cpp
cppcache/src/SerializationRegistry.cpp
cppcache/test/CMakeLists.txt
cppcache/test/GatewaySenderEventCallbackArgumentTest.cpp

It was observed that when having two sites, with a client connected to each site, there were serialization errors in the clients when handling received events. The cause is that GatewaySenderEventCallbackArgument objects are sent as part of the events, but this class is not known by the C++ client.
This PR allows the C++ clients to deserialize the class.
Using the same setup with using two java clients, I have observed that the GatewaySenderEventCallbackArgument objects are received and deserialized correctly, but it seems they are not used. This is why this PR is not including any other code related with the GatewaySenderEventCallbackArgument in the C++ clients.

GEODE-8344: Add GatewaySenderEventCallbackArgument class

---

cppcache/integration/test/CMakeLists.txt
cppcache/integration/test/PdxInstanceFactoryTest.cpp
cppcache/src/PdxTypeRegistry.cpp

A segmentation fault is produced when `PdxInstanceFactory::create()` is called by several threads that are registering the same new pdx type.
The core is produced here:
```
void PdxInstanceImpl::toDataMutable(PdxWriter& writer) {
auto pt = getPdxType();
std::vector<std::shared_ptr<PdxFieldType>>* pdxFieldList =
pt->getPdxFieldTypes();
```
`getPdxType()` returns `nullptr`, so in the next line, there is segmentation fault when calling `pt->getPdxFieldTypes()`.
I have seen the problem appears when `PdxInstanceImpl::getPdxType()` calls `PdxTypeRegistry::getPdxType()` and this method returns `nullptr` due to it is not able to found an entry in its `typeIdToPdxType_` map. But I have verified that at that point, the corresponding entry in `pdxTypeToTypeId_` map exists, so the maps were not …

GEODE-8436: Several threads calling PdxInstanceFactory::create() causes seg fault

---

cppcache/integration/test/SNITest.cpp

- It's being run in the test suite due to a typo

GEODE-8443: Disable Windows SNI test as intended

---

clicache/src/CacheFactory.cpp

This fixes a longstanding AppDomain bug that was introduced back in March 2017, wherein the AppDomainContext was being initialized after the cache was created.
I've tested the fix this by utilizing a simple Asp.NET web application running in IIS. Prior to the fix, the exception ("Cannot pass gchandle across AppDomains") appears in the log file. I have seen the exception occur in the following threads: "NC MC Thread" (Manage Connections) and "NC CMDService Thread". With the fix I can no longer generate this exception in IIS or IIS Express.

GEODE-8441: AppDomainContext was initialized too late

---

clicache/src/Pool.cpp
clicache/src/Pool.hpp
clicache/test2/Tests2.cs
cppcache/include/geode/Pool.hpp
cppcache/src/Pool.cpp

Since the .NET API is a thin wrapper around the C++ API, all we really need to test in this layer is that the sni parameters are passed properly to the C++ layer.
This PR adds a new unit test in the new google test framework. Also includes new accessor functions to the pool API to get and set the sni parameters.

GEODE-8398: Add sni unittest for dotnet

---

clicache/integration-test2/SNITests.cs
cppcache/integration/test/SNITest.cpp

-use docker system prune -f to clean up networks and stopped containers
Noticed when trying to `docker rmi` the downloaded images and it said there were still containers with them.

GEODE-8470: Properly stop running containers in SNI

---

tests/javaobject/LatestProp.java

This [commit](https://github.com/apache/geode/commit/d9d13100ae11e2eba8a6428fad29007388680b43#diff-a377b15d2036a2fc9072c1915c7f0ed4L83) removed getBuildDate() in the java code, causing geode native develop to fail to compile with geode develop

Remove  GemFireVersion.getBuildDate()

---

clicache/acceptance-test/SNITests.cs
cppcache/acceptance-test/SNITest.cpp

This cleans up any docker containers at the beginning of each test in case of a test failure that leaves docker containers up.

GEODE-8449: Cleanup containers before each test

---

tools/gnmsg/client_messages.py

Found a log file this morning from an app that was calling `getKeys()` and `getAll()`, and discovered these message that hadn't yet been added to the parser.
@alb3rtobr @mreddington @davebarnes97 @karensmolermiller @dihardman

GEODE-8524: Add support for KEY_SET and GET_ALL_70 messages

---

cppcache/integration-test/resources/cacheWriterTransaction1.xml
cppcache/integration/test/CMakeLists.txt
cppcache/integration/test/CacheWriterTest.cpp
cppcache/src/RegionCommit.cpp
tests/javaobject/CacheWriterTransaction.java

Client is fixed in a way that ignores all regions enlisted within
transaction that client doesn't have configured. This behavior is
aligned with the java client, since same thing is done there.

GEODE-8530: Fix for coredump during tx commit

---

cppcache/src/TcpConn.cpp
cppcache/src/TcpConn.hpp

- Calling get_host_name() in TcpConn::connect involves a system call that
might take several seconds to complete.
- So endpoint is stored instead upon TcpConn construction and used later
instead of making the system call.

GEODE-8548 Avoid hostname resolution in TcpConn

---

tools/gnmsg/client_message_decoder.py
tools/gnmsg/client_messages.py
tools/gnmsg/server_message_decoder.py

- This would be called, and thus throw an exception, for client logs using AuthInitialize
- Also added a new entry to version lookup for regex function dispatcher.
@mreddington @davebarnes97 @dihardman @karensmolermiller @alb3rtobr

GEODE-8569: Add missing method to ClientMessageDecoder

---

tools/gnmsg/server_messages.py

I tried the gnmsg tool with a client log file connecting to a cluster that contains a partition region with a partition resolver, which caused an exception.
With this change, it is possible to parse the partition resolver name. Still pending to parse the list of fixed partition attributes, maybe in other ticket...
This is how the message looks like after parsing my log file:
```
{
"message": {
"Timestamp": "16:47:55.225776",
"Connection": "0",
"Direction": "<---",
"Type": "RESPONSE_CLIENT_PARTITION_ATTRIBUTES",
"Length": 80,
"Parts": 3,
"TransactionId": -1,
"SecurityFlag": 0,
"BucketCount": {
"Size": 5,
"IsObject": 1,
"Data": {
"DSCode": "CacheableInt32",
"Value": 113
}
},
"ColocatedWith": {
"Size": 0,
"IsObject": 0
},
"PartitionResolverName": {
"Size": 60,
"IsObject": 1,
"Data": { …
```

GEODE-8578: Parse partition resolver in RESPONSE_CLIENT_PARTITION_ATTRIBUTES message

---

CMakeLists.txt

Seems like we don't need this cop out any more!  Or at least on the mac, we'll see what Travis says about clang on linux

Enforce header hygiene

---

cppcache/integration/framework/GfshExecute.cpp

This is a fix to the new C++ test framework. We were throwing pointers.

GEODE-8580: Don't throw pointers in GfshExecute

---

cppcache/integration/test/PartitionRegionOpsTest.cpp
cppcache/src/Log.cpp
cppcache/src/ThinClientPoolDM.cpp

This ticket is an improvement over GEODE-8231:
> If a C++ client connected to a cluster is sending operations to a partitioned region and one of the server goes down, the client keeps trying to send operations to the down server. This can be observed in the logs by a continuous flow of lines containing: "IO error in handshake with endpoint..."
After that improvement, the c++ client removes the metadata info of the failing server once the "IO error in handshake" is received.
But it has been observed that before that error is received, "timeout error" can be returned. So the client will try to reconnect until the "IO error in handshake" is received.
This ticket aims to extend the GEODE-8231 solution so the client removes the server metadata information when a timeout is received.

GEODE-8565: Remove bucketServerLocation if timeout error

---

cppcache/src/AuthenticatedView.cpp
cppcache/src/Cache.cpp
cppcache/src/CqQueryImpl.cpp
cppcache/src/CqService.cpp
cppcache/src/statistics/OsStatisticsImpl.cpp
cppcache/src/statistics/Statistics.cpp

MacOS apparently flags more of these than our Linux builds, so this fixes up Mac builds.
@mreddington @davebarnes97 @dihardman

GEODE-8604: Fix documentation errors on Mac build

---

cppcache/src/ThinClientPoolDM.cpp

This PR removes the exclusive access to the creation/closing of pool connections that uses the mutex that is also used to grant exclusive access to the ConnectionQueue.
That way access to the connection queue is not impaired when there are problems creating connections.

GEODE-8613: Removing exclusive access to creation/closing of pool connections

---

CMakeLists.txt
cppcache/integration-test/fw_dunit.hpp
cppcache/integration-test/testDataOutput.cpp
cppcache/integration-test/testOverflowPutGetSqLite.cpp
cppcache/integration-test/testSerialization.cpp
cppcache/integration-test/testThinClientRemoveOps.cpp
cppcache/src/dllmain.cpp
cppcache/test/ByteArrayTest.cpp
cppcache/test/CacheableKeysTest.cpp
cppcache/test/DataInputTest.cpp
tests/cpp/fwklib/UDPIpc.hpp

Here's some flaky CI passes in [Windows](https://github.com/moleske/geode-native/actions/runs/298200790), [Ubuntu](https://github.com/moleske/geode-native/actions/runs/298200789), and [Mac ](https://github.com/moleske/geode-native/actions/runs/298200788)for showing it is working.
The `do...while` change in `fw_dunit.hpp` is because I got angry at some unneeded semicolons in one of the files so I went ahead and wrapped the macro.  If folks don't like it I guess I can revert it and be sad about it on my own.

GEODE-8596: Enforce no old style cast

---

CMakeLists.txt

Another Clang compiler warning that is not needed to be skipped anymore (assuming that travis ci works, it seemed alright on the local machine)

Enforce no-sign-conversion

---

clicache/acceptance-test/SNITests.cs
cppcache/acceptance-test/SNITest.cpp
cppcache/integration/test/CMakeLists.txt
cppcache/integration/test/RegisterKeysTest.cpp
cppcache/src/MapSegment.cpp

This adds a new DropProxy test to the docker based acceptance tests for .NET.
Note: This test will only run on Windows platforms that have docker and docker-compose installed.

GEODE-8157: Add DropProxy acceptance test for .NET

---

cppcache/acceptance-test/SNITest.cpp

Bad variable name
Since https://github.com/apache/geode-native/pull/674 was merged before it was allowed to finish testing, a broken build is now committed.  And then my CI got sad

GEODE-8157: Make SNITest.cpp compile

---

clicache/src/Cache.hpp

Add missing documentation for Cache::GetPoolManager() and Cache::GetPoolFactory().

GEODE-8678: Add missing API docs

---

clicache/integration-test2/CMakeLists.txt
clicache/integration-test2/DataInputTest.cs
clicache/src/DataInput.cpp
clicache/src/DataInput.hpp
clicache/src/native_unique_ptr.hpp

The CLI DataInput object has two ctors, one of which copies the passed-in buffer parameter via new[] and one of which doesn't.  In the event that the former is called, the buffer is leaked when the object is deleted/Disposed.
@mreddington @dihardman @karensmolermiller @davebarnes97

GEODE-8647: Stop leaking buffer in CLI DataInput 

---

docs/docker/view-docs.sh

One change that I think should have been included in the previous PR for this ticket.
Adds a `bundle exec` prefix before `rackup` in the view-docs.sh script. Should improve the user experience.

GEODE-8676: Update Bookbindery

---

cppcache/integration/test/PartitionRegionOpsTest.cpp
cppcache/src/ThinClientPoolDM.cpp
cppcache/src/ThinClientPoolDM.hpp

The following integration test cases under
integration/test (new integration tests)
ar flaky (do not
fail normally when run locally but fail very often
when run in CI).
- PartitionRegionOpsTest.getPartitionedRegionWithRedundancyServerGoesDownSingleHop
- PartitionRegionOpsTest.putPartitionedRegionWithRedundancyServerGoesDownSingleHop
There were two reasons that can make them fail.
One of them is that sometimes the connections to the server have expired
before the server is restarted and therefore, when traffic is sent
to the restarted server, no errors are found. To fix this,
the pool configuration for the test client
has been changed so that connections do not expire.
The other reason is that sometimes the error in the connection is
found by the ping thread that is invoking the …

GEODE-8688: Fix flaky C++ native client integration tests

---

docs/geode-native-book-cpp/redirects.rb
docs/geode-native-book-dotnet/redirects.rb
docs/geode-native-docs-cpp/client-cache-ref.html.md.erb
docs/geode-native-docs-dotnet/client-cache-ref.html.md.erb

Added a language-agnostic redirect to which the appropriate API reference can be assigned.
Applied the change to both .NET and C++ user guides, for consistency across-the-board.

GEODE-8713: .NET user guide - API reference links point to C++ API

---

docker/Dockerfile

- As latest tag for ubuntu base image was recently change from 18.04 to
20.04 it seems that some libraries version changed, like for example
libc++.
- As it seems with this new version libc++ headers are either not
anymore located within /usr/include/c++/v1 or the symlink is missing.
- So in order to solve that a symlink is manually created to ensure
clang is able to find libc++ headers.

GEODE-8724: Fix compilation using docker image

---

docs/geode-native-book-cpp/redirects.rb
docs/geode-native-book-dotnet/redirects.rb
docs/geode-native-docs-cpp/about-client-users-guide.html.md.erb
docs/geode-native-docs-cpp/client-cache-ref.html.md.erb
docs/geode-native-docs-dotnet/about-client-users-guide.html.md.erb
docs/geode-native-docs-dotnet/client-cache-ref.html.md.erb

The previous fix failed when publishing to the Geode website (vs cf push to a PWS server).
Modified the website's `.htaccess` file to handle redirects there.
Changed `cppdocs` and `dotnetdocs` placeholders to `cppapiref` and `dotnetapiref`, respectively, to avoid recursion problems.
Updated source files (about* and client-cache-ref*) to use the new placeholders.
Tested locally and pushed to the Geode site to verify that it works in both environments.

GEODE-8713: user guide API reference links - fix redirects for Geode website

---

cppcache/integration/framework/Gfsh.cpp
cppcache/integration/framework/Gfsh.h

Adds support to the new C++ test framework for executing the gfsh command: execute function
Note: The new .NET test framework already has this functionality.

GEODE-8775: Add gfsh execute function support

---

cppcache/src/TcrConnection.cpp
tools/gnmsg/chunked_message_decoder.py
tools/gnmsg/server_message_decoder.py

- This is still not a complete implementation, but it's close enough to go in, I think.  It should handle all except cases where an app has chunked responses coming in on multiple simultaneous threads, which is (I think) kind of an obscure scenario at the moment.
- The tool doesn't yet attempt to parse any of the content of a chunked response, but rather just prints a summary of the chunk info, e.g.:
```
{
"message": {
"Type": "RESPONSE",
"Connection": "0x7fe7e9704320",
"Direction": "<---",
"Parts": 1,
"TransactionId": -1,
"ChunkInfo": [
{
"Chunk0": {
"ChunkLength": 2410,
"Flags": 0
}
},
{
"Chunk1": {
"ChunkLength": 682,
"Flags": 1
}
}
]
}
}
```
@mreddington @albertogpz

GEODE-8532: parse chunked responses in gnmsg tool

---

cppcache/src/CacheableString.cpp
cppcache/src/util/size_tracking_allocator.hpp
cppcache/test/CacheableStringTests.cpp

- objectSize was not taking into account null-terminator character,
which as of C++11, as stated in § 21.4.7.1, should be included at
the end of the same string character sequence.
- Also, in those cases in which SSO applied, the returned size was
higher than the actual one.
- A parametrized UT was added to check objectSize is returning the
right size. Note that no fixed sizes are part of such test, given
that each std::string implementation could have a different SSO
size.

GEODE-8756: Fix CacheableString::objectSize

---

clicache/integration-test2/SerializationTests.cs
cppcache/integration/test/CMakeLists.txt
cppcache/integration/test/DataSerializableTest.cpp
cppcache/integration/test/Position.cpp
cppcache/integration/test/Position.hpp
cppcache/integration/test/PositionKey.cpp
cppcache/integration/test/PositionKey.hpp
tests/javaobject/cli/InstantiateDataSerializable.java
tests/javaobject/cli/PositionKey.java

This adds a new C++ serialization test for using a class as a key.
Notes:
* This test leverages the new gfsh execute function support in the C++ test framework.
* A .NET serialization test for using a class as a key has been added in a previous PR.

GEODE-8562: Adds new C++ test for using a class as a key

---

dependencies/ACE/CMakeLists.txt

This change allows the Windows SDK version for ACE to be specified using CMAKE_SYSTEM_VERSION, which can be set appropriately for the target machine.
Our CI uses Windows SDK version 10.0.16299.0,, so passing -DCMAKE_SYSTEM_VERSION=10.0.16299.0 to the cmake config step fixes our CI build failure on Windows. Note, this also requires a change to our CI code which generates the cmake command.

GEODE-8820: Fix Windows build for latest ACE

---

cppcache/src/TcpConn.cpp

After replacing ACE_SOCK with boost::asio a
significant performance degradation has been observed
in send and receive operations.
The cause has been some log debug calls added to the
TcpConn::send and TcpConn::receive that took as
input a stringstream previously created.
After changing these logs to not use the
stringstream, the performance of the
native client has returned to the original
figures.

GEODE-8831: Fix performance degradation after changing to boost::asio

---

CMakeLists.txt
cppcache/integration/test/CMakeLists.txt

- SCOPED_TRACE in gtest causes this error, so only allow in that scope
Also sorted the tests listed because it bothered me that it was really close to sorted but wasn't

GEODE-8842: Limit no-used-but-marked-unused to new integration tests

---

cppcache/integration/test/TransactionsTest.cpp
cppcache/src/InternalCacheTransactionManager2PCImpl.cpp

- Exceptions were not correctly handled during transaction operations,
leading to the derived type of the exception to be lost on the
internal source calls.
- Problem was that in the process of capturing an re-throwing the
exceptions, a copy of its more generic type, `Exception` was created
and passed throught, instead of the original exception. This has been
sorted out.
- Also, several integration test were added, in order to ensure that
the correct type of exceptions are thrown when an error occurs while
executing transsactions operations.
---
It seems C++ have some particular syntax when it comes to rethrowing exceptions, as can be seen here: https://stackoverflow.com/a/2360673/14434972
Hence, the problem was that a copy of type **Exception** was being thrown, instead of the original …

GEODE-8830: Fix exception handling in transactions

---

CMakeLists.txt

Since https://github.com/apache/geode-native/pull/608 got rid of this warning on clang, we can get rid of it on windows.  Though let me know if I really should make a new jira instead of reusing the old one

GEODE-8207: Enforce no unknown pragma on windows

---

cppcache/integration-test/BBNamingContext.cpp
cppcache/integration-test/CMakeLists.txt
cppcache/integration-test/fw_dunit.cpp
cppcache/integration-test/fw_dunit.hpp

- old behavior allowed other parts of the code to treat this as a
warning and not an error
- fix up BBNamingContext and fw_dunit just to make it easier in ignoring
this in old integration test files
Using old GEODE-8469 JIRA since this is fixing a mistake in that, but feel free to tell me to make a new one

GEODE-8469: Add -Wno-missing-variable-dclarations to specific targets instead of _WarningsAsError

---

cppcache/src/EventId.cpp
cppcache/src/EventId.hpp
cppcache/src/EventIdMap.cpp

- Use Meyers singleton pattern for global singleton (threadId), and
thread local singleton EventIdTSS
- rename all member variables in EventId and EventIdTSS classes
- clean up logic slightly around global threadId atomic var
- rename EventId getter methods for clarity

GEODE-8887: Refactor EventIdTSS class

---

tools/gnmsg/client_message_decoder.py
tools/gnmsg/client_messages.py
tools/gnmsg/command_line.py
tools/gnmsg/gnmsg.py
tools/gnmsg/gnmsg_globals.py
tools/gnmsg/protocol_state.py
tools/gnmsg/read_values.py
tools/gnmsg/server_message_decoder.py
tools/gnmsg/server_messages.py

Server REPLY and RESPONSE messages can come back in response to a number of different client messages, and the contents of the server message differ based on the original request.  This introduces a bit of global state so that the server message parser can see what the last client message was for this thread, and parse the response accordingly.  Out of necessity, the first two responses parsed are the REPLY to a PUT and the RESPONSE to CONTAINS_KEY.

GEODE-8871: parse server response messages for PUT and CONTAINS_KEY

---

dependencies/ACE/CMakeLists.txt

I didn't really want to update ACE, but I really wanted to be able to [build on MacOS 11 (Big Sur)](https://github.com/moleske/geode-native/runs/1773671597?check_suite_focus=true) so 🤷‍♀️ 
Seems to work in my tests for the existing operating systems, but will let folks with fancy pipelines tell me I'm wrong

GEODE-8884: Update ACE to 7.0.0

---

cppcache/src/Log.cpp
cppcache/test/LoggingTest.cpp

Instead of using `boost::filesystem::portable_file_name` to police log file names, try/catch boost and std exceptions when creating log file and report an error via IllegalArgumentException.

Geode 8892 loosen log file name rules

---

dependencies/sqlite-netFx/CMakeLists.txt
dependencies/sqlite/CMakeLists.txt

Since I was updating ACE, figured I should check the rest of the dependencies.  Seems good on the [operating systems that I tested on](https://github.com/moleske/geode-native/pull/34/checks).
As an aside, has anyone looked at trying to use [dependabot ](https://github.com/dependabot/dependabot-core) to create a CMake dependency updater?  I've seen a few people fork and run their own dependabot to keep dependencies up to date in a build system that dependabot didn't support.  I haven't looked too closely cause I didn't really want to muck with ruby.

GEODE-8900: Bump sqlite and sqlite-netfx to latest

---

cppcache/src/TXId.cpp
cppcache/src/TXId.hpp
cppcache/test/CMakeLists.txt
cppcache/test/TXIdTest.cpp

Issue: Transaction commit fail when m_transactionID integer overflows to
negative value, because server interprets negative value as
non-transactional message.
Fix: Client is impacted to reset transactionID to one when INT_32MAX
value is reached in order to avoid overflow.

GEODE-8874: Fix for transaction commit failure

---

clicache/src/CacheableString.hpp
examples/dotnet/classaskey/PhotosKey.cs
examples/dotnet/classaskey/Program.cs
examples/dotnet/classaskey/README.md
examples/utilities/PhotosKey.java

This PR updates the .NET ClassAsKey example to use only standard .NET types. Additional tweaks include:
- switch to new Objects.Hash() to ensure hashCodes mache between client and server
- remove public from CacheableString since no longer needed
- print matching hashCode output and add to README.md

GEODE-8562: Use standard .NET types in .NET ClassAsKey Example

---

cppcache/src/Log.cpp
cppcache/src/util/Log.hpp
cppcache/test/LoggingTest.cpp

logger wasn't calculating size of existing logs at initialization, so stopping and restarting an app without deleting logs would cause the logger to 'grow' used disk space by up to `log-disk-space-limit` each iteration.
Also added appropriate tests, and fixed a default filename issue.
Co-authored-by: Matthew Reddington <mreddington@vmware.com>

GEODE-8929: fix 'leaked disk space' issue in logger

---

cppcache/test/LoggingTest.cpp

Was failing to build on Mac
PR https://github.com/apache/geode-native/pull/746 caused a failure on Mac only it seems due to `SetUp` function from gTest not using override correctly.  Since the body was commented out and `scrubTestLogFiles` is used in `TearDown`, I just deleted the function to solve the problem

GEODE-8949: Fix broken build inconsistent-missing-override

---

cppcache/src/EventId.cpp

- memId isn't a string, need to convert it first or we'll log garbage.

GEODE-8994: Fix log line in EventId ctor

---

cppcache/src/util/exception.hpp

- Whenever calling throwExceptionIfError macro it can happen that calls
are duplicated. Hence the macro has been replaced by a inlined
function.

GEODE-8973: Fix calls dup on exception handling

---

tools/gnmsg/gnmsg.py
tools/gnmsg/protocol_state.py
tools/gnmsg/server_message_decoder.py

"receiving header"
- This association wasn't happening if the connection on this thread
hadn't already sent a message.  When that happened, we'd drop the
trace with the message body and mess up the state machine.

GEODE-9008: associate tid with connection when parsing message about

---

tools/gnmsg/server_messages.py

- No longer need to grovel server logs for this, which is a nice
improvement.

GEODE-9053: Decode EXCEPTION message from server in gnmsg

---

cppcache/src/CqService.cpp
cppcache/src/CqService.hpp
cppcache/src/TcrChunkedContext.hpp
cppcache/src/TcrConnection.cpp
cppcache/src/TcrConnection.hpp
cppcache/src/TcrConnectionManager.cpp
cppcache/src/TcrConnectionManager.hpp
cppcache/src/TcrEndpoint.cpp
cppcache/src/TcrEndpoint.hpp
cppcache/src/TcrMessage.cpp
cppcache/src/TcrMessage.hpp
cppcache/src/TcrPoolEndPoint.cpp
cppcache/src/TcrPoolEndPoint.hpp
cppcache/src/ThinClientBaseDM.cpp
cppcache/src/ThinClientPoolDM.cpp
cppcache/src/ThinClientPoolDM.hpp
cppcache/src/ThinClientPoolHADM.cpp
cppcache/src/ThinClientPoolHADM.hpp
cppcache/src/ThinClientRedundancyManager.cpp
cppcache/src/ThinClientRedundancyManager.hpp
cppcache/src/util/concurrent/binary_semaphore.cpp
cppcache/src/util/concurrent/binary_semaphore.hpp

- In order to progress in the task of getting rid of ACE library, a
replacement is needed for ACE_Semaphore.
- Currently there is no suitable Boost alternative and C++
implementation is not in the standard until C++20. Hence STL like
implementation was added as binary_semaphore.
- Replaced all instances of ACE_Semaphore by binary_semaphore.
- Fixed ill semaphore logic in several cases in which running token was
checked twice without any specific need.

GEODE-9056: Replace ACE_Semaphore

---

cppcache/include/geode/ExceptionTypes.hpp
cppcache/integration/test/PdxInstanceTest.cpp
cppcache/integration/test/mock/CacheListenerMock.hpp
cppcache/src/PdxHelper.cpp
cppcache/src/PdxHelper.hpp
cppcache/src/PdxInstanceFactory.cpp
cppcache/src/PdxInstanceImpl.cpp
cppcache/src/SerializationRegistry.cpp

- In those scenarios in which Pdx serialization occurs while
PdxTypeRegistry is being cleaned up, it happened that NC crashed
because it couldn't find the PdxType.
- This commit adds retries to Pdx serialization, and in case retries
are exhausted, UnknownPdxTypeException is thrown, so it can be
handled by the user.
- Implemented IT to verify this behaviour.

GEODE-8968: Fix toDataMutable coredump

---

docs/geode-native-book-cpp/redirects.rb
docs/geode-native-book-dotnet/redirects.rb
docs/geode-native-docs-cpp/configuring/config-client-cache.html.md.erb
docs/geode-native-docs-dotnet/configuring/config-client-cache.html.md.erb

The page "Configuring the Client Cache" contains two links to the API docs, one for C++, one for .NET. The links didn't connect, now they do.

GEODE-6816: Geode Native Client user guide: Fix broken API links

---

cppcache/integration/test/RegionPutAllTest.cpp
cppcache/src/ClientMetadataService.cpp

- This matches the behavior of the Java client
- Our current code to "tack on" values that we don't have metadata
for will sometimes result in EventIds reaching a server out-of-order,
causing them to be dropped and resulting in data loss.  Resorting
to multi-hop avoids this altogether.

GEODE-9147: Revert to multi-hop PUTALL in the face of missing metadata

---

dependencies/boost/CMakeLists.txt

> Bintray is “sunsetting” on the 1st of May. 
> At that time, you will be unable to download boost releases from there.
> Before that time, their service will be occasionally interrupted.
> 
> 
> We will be updating the web site before then, but the new location is:
> 
> https://boostorg.jfrog.io/artifactory/main/release/
> 
> So instead of downloading from:
> 	https://dl.bintray.com/boostorg/release/1.76.0/source/boost_1_76_0.tar.gz
> 
> You should download from:
> 	https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz
>

Replaced deprecated bintray addresses.

---

cppcache/src/util/concurrent/binary_semaphore.cpp
cppcache/src/util/concurrent/binary_semaphore.hpp
cppcache/test/ExpiryTaskTest.cpp
cppcache/test/gmock_extensions.h

- Solved a potential race condition in ExpiryTaskTest UTs TS.
condition_variable was replaced by a binary_semaphore.
- Implemented try_acquire_for binary_semaphore operation.

GEODE-9179: Solve potential race conditions in UTs

---

cppcache/src/TcrEndpoint.cpp
cppcache/src/TcrMessage.cpp
cppcache/src/TcrMessage.hpp
cppcache/test/TcrMessageTest.cpp

- Prevents a leak at shutdown, ensures object is properly destroyed.

GEODE-9193: Use local object variable for PING messages.

---

ci/docker/clang-tools/Dockerfile
docker/centos-8/Dockerfile
docker/rhel-8/Dockerfile

- Due to some changes in base images and in the CMake artifact names,
docker build is not working for the following images:
* rhel-8
* centos-8
* clang-tools
- This commit solves all build issues.

GEODE-9212: Fix docker images build

---

cppcache/integration/test/RegisterKeysTest.cpp
cppcache/src/ConcurrentEntriesMap.cpp
cppcache/src/ConcurrentEntriesMap.hpp
cppcache/src/EntriesMap.hpp
cppcache/src/LocalRegion.cpp
cppcache/src/LocalRegion.hpp
cppcache/src/RegionInternal.cpp
cppcache/src/RegionInternal.hpp
cppcache/src/ThinClientPoolHADM.cpp
cppcache/src/ThinClientPoolHADM.hpp
cppcache/src/ThinClientRedundancyManager.cpp
cppcache/src/ThinClientRegion.cpp
cppcache/src/ThinClientRegion.hpp

- Consistent failures in legacy C++ test testThinClientHADistOps in CI
This reverts commit 33c960d6dce07a3dc04f9ed6d020ce35d2033c79.

Revert "GEODE-8991: Implement cached region clean up (#757)"

---

cppcache/src/CacheImpl.cpp
cppcache/src/CqService.cpp
cppcache/src/CqService.hpp
cppcache/src/RegionInternal.hpp
cppcache/src/RemoteQueryService.cpp
cppcache/src/RemoteQueryService.hpp
cppcache/src/TcrEndpoint.cpp
cppcache/src/TcrMessage.cpp
cppcache/src/TcrMessage.hpp
cppcache/src/ThinClientHARegion.cpp
cppcache/src/ThinClientHARegion.hpp
cppcache/src/ThinClientPoolHADM.cpp
cppcache/src/ThinClientPoolHADM.hpp
cppcache/src/ThinClientRedundancyManager.cpp
cppcache/src/ThinClientRedundancyManager.hpp
cppcache/src/ThinClientRegion.cpp
cppcache/src/ThinClientRegion.hpp

- Remove static endpoint disconnected message
- use dynamically allocated message for this, a la other messages
- no longer leak an instance at shutdown, no more special case code for
this message when deleting messages.
- Remove some really unfortunate abbreviations in a couple of function and variable names.

GEODE-9200: Clean up DisMess

---

docker/ubuntu-20.04/Dockerfile

- Currently there is a CI pipeline for Ubuntu 20.04. However, there is
not a build docker image for Ubuntu 20.04.
- This commit adds a build docker image based on Ubuntu 20.04, so CI
verification can be reproduced in a local environment.

GEODE-9213: Add Ubuntu 20.04 build docker image

---

cppcache/src/ClientMetadataService.cpp

Sending GET_CLIENT_PR_METADATA to a server for a replicated region generated an EXCEPTION response message, which the native client would then ignore.  Convention in the Java client is to check for a bucket count of -1, indicating replicated region, and skip the metadata request in that case.
@gaussianrecurrence

GEODE-8405: Don't ask for metadata for replicated regions

---

clicache/integration-test2/DataInputTest.cs

This test was flaky in the VS 2019 build in the new CI. Reenabling now that we have more stability.

GEODE-8939: Reenable CreateDisposeAndCheckForMemoryLeaks in the new framework

---

cppcache/integration/test/RegisterKeysTest.cpp
cppcache/src/ConcurrentEntriesMap.cpp
cppcache/src/ConcurrentEntriesMap.hpp
cppcache/src/EntriesMap.hpp
cppcache/src/LocalRegion.cpp
cppcache/src/LocalRegion.hpp
cppcache/src/RegionInternal.cpp
cppcache/src/RegionInternal.hpp
cppcache/src/ThinClientPoolHADM.cpp
cppcache/src/ThinClientPoolHADM.hpp
cppcache/src/ThinClientRedundancyManager.cpp
cppcache/src/ThinClientRegion.cpp
cppcache/src/ThinClientRegion.hpp
cppcache/src/util/concurrent/binary_semaphore.hpp

- Whenever subscription redundancy is lost cached regions are supposed
to be cleaned up. This commit implements interest recovery to achieve
precisely that.
- Whenever subscription redundancy is lost all entries with interest
registered are cleaned up.
- Implemented an optimization for regions which have interest
registered to all keys.
- ITs implemented to verify the functionality.
- Adapted RegisterAllWithConsistencyDisabled test to work with the
modified CacheListener mock.
- As noted for RegisterAllWithConsistencyDisabled case, a fail-safe
have been added to avoid a rare race condition.
- Fixed coredump when trying to clear interest registry keys for
regions with caching disabled.
- Fixed exception whenever cleaning up cached region which interest
list is a set of keys and some of …

GEODE-8991: Implement cached region clean up

---

cppcache/integration-test/CMakeLists.txt
cppcache/integration-test/ThinClientFailover2.hpp

This test is important because it validates CACHING_PROXY with client notifications enabled for multiple client caches.

GEODE-9236: Fix testThinClientFailover2 and reenable

---

cppcache/integration-test/CMakeLists.txt
cppcache/integration-test/ThinClientPutAllWithCallBack.hpp
cppcache/integration-test/testThinClientLargePutAllWithCallBackArg.cpp

This test is important because it tests putAll with a callBack argument.

GEODE-9246: Fix large putAll with callBack

---

cppcache/integration-test/CMakeLists.txt
cppcache/integration-test/testThinClientRemoveOps.cpp

This is an important test because it is a quite extensive test of the Region API. It has not been run in a very long time, because it failed. With the recent fix to TcrMessageDestroy (PR #804), this test now passes.

GEODE-9259: cleanup and reenable testThinClientRegionOps

---

ci/docker/clang-tools/Dockerfile

Homebrew formulae for MacOS  installs v12 of clang tools by default now, and once again it is not compatible with the previous version.  This installs v12 on our Docker image, so we don't have to jump through more hoops for Mac development.

Update clang tools version in CI

---

ci/lib/templates.lib.yml
cppcache/src/RegionAttributes.cpp

This seems to reduce the incidence of failure in the integration test that's causing problems with VS2019/Windows Server 2019 (CqPlusAuthInitializeTest.putInALoopWhileSubscribedAndAuthenticated).

Reduce parallelism in integration tests to 4

---

cppcache/integration/test/RegisterKeysTest.cpp
cppcache/integration/test/ServerDisconnectWithListener.cpp
cppcache/integration/test/gmock_actions.hpp

- Solved a possible race condition in ServerDisconnectWithListener TS
due to the fact that there was no check to verify the server was
actually stopped.
- Also added gmock_actions helper to avoid duplication.
- Modified RegisterKeysTest to use gmock_actions helper.

GEODE-9321: Fix possible race condition on ITs

---

clicache/src/CMakeLists.txt
clicache/src/Serializable.cpp
clicache/src/String.hpp
clicache/test/CMakeLists.txt
clicache/test/SerializableTests.cpp
clicache/test/StringTests.cpp
dependencies/ACE/CMakeLists.txt

Adds new String.hpp similar to C++ client's string.hpp.
Converts String to std::string via UTF-16 to UTF-8 transform.
Converts std::string to String via UTF-8 to UTF-16 transform.
Adds basic unit tests for String.hpp methods.
Adds basic unit tests for Serializable.
Splits the .NET library into objects and assembly so that unit tests
can link directly against the objects to avoid symbol export issues
crossing C++/CLI layers.
Fixes ACE PDB location so it can be correctly included in dependent projects.

GEODE-9412: Fixes translation of String between .NET and C++

---

cppcache/src/ThinClientRegion.cpp

- Latest compiler/runtime on RHEL-8 causes an order-of-initialization
bug for this static regex, and will core dump at app startup for
optimized builds.
- Changing to local static ensures regex variable isn't initialized
until the first time we use it, long after all static initializers are
called.

GEODE-8891: Move static regex in ThinClientRegion

---

cppcache/integration/test/TransactionCleaningTest.cpp

- Solved a potential race condition in TransactionCleaningTest TS
due to the fact that no checks were performed after starting/stopping
the server.

GEODE-9322: Fix possible race condition on new ITs

---

clicache/src/Cache.cpp
clicache/src/CacheFactory.cpp
clicache/src/CqQuery.cpp
clicache/src/DistributedSystem.cpp
clicache/src/Execution.cpp
clicache/src/LocalRegion.cpp
clicache/src/Properties.cpp
clicache/src/Query.cpp
clicache/src/QueryService.cpp
clicache/src/Region.cpp
clicache/src/Serializable.cpp
clicache/src/impl/AuthenticatedView.cpp
clicache/src/impl/ManagedCacheableKey.cpp
clicache/src/impl/PdxManagedCacheableKey.cpp

...where applicable
- region names can be Unicode, cacheable keys/values, etc.  Most of the
rest don't need this, because they're never Unicode.

GEODE-9412: Fix up marshaling of (potential) Unicode strings

---

cppcache/src/Log.cpp

From the bug description:  "The native client logger was rewritten several months ago to use, among other things, `std::put_time` when formatting log strings, specifically using the "%Z" formatting for timezone. The documentation for this formatting says "writes locale-dependent time zone name or abbreviation, or no characters if the time zone information is not available," and indeed it does. We just received a log file from a customer machine in APJ region, i.e. locale is set to something like Traditional Chinese. These strings are dumped into the log file as is, in some unknown MBCS encoding, and contain invalid utf-8 start codes, throwing off our Python-based parsing tool."
The lower case `%z` format specifier just gives an offset from GMT, e.g. `-0700`, which might still be useful …

GEODE-9487: Use locale-independent format specifier for timezone in

---

clicache/integration-test2/GarbageCollectCache.cs

The heuristic was a bit too strict. With 25 iterations, there was no reason to have the range be so small.

GEODE-9472: Relax the ratio of before and after threads.

---

ci/base/base.yml
dependencies/ACE/CMakeLists.txt

This reverts commit 95c6b5ee53f9c8b7525fd34885cd9f3284d579d4.  Windows builds are breaking, and it looks like we should really be fixing the SDK version at a certain point and only updating intentionally, rather than by virtue of picking up whatever's the latest from Microsoft.

Revert "GEODE-9501: Works with toolset Microsoft v142 (#841)"

---

dependencies/ACE/CMakeLists.txt

This PR updates CMakeLists.txt for ACE to support Visual Studio 2019.

GEODE-9511: Update ACE cmake config for VS2019

---

docs/geode-native-docs-dotnet/continuous-queries.html.md.erb
docs/geode-native-docs-dotnet/function-execution.html.md.erb
docs/geode-native-docs-dotnet/preserving-data/config-durable-interest-keys.html.md.erb
docs/geode-native-docs-dotnet/regions/registering-interest-for-entries.html.md.erb
docs/geode-native-docs-dotnet/remote-queries.html.md.erb
docs/geode-native-docs-dotnet/serialization/dotnet-serialization/dotnet-pdx-autoserializer.html.md.erb
docs/geode-native-docs-dotnet/serialization/dotnet-serialization/pdx-serializable-examples.html.md.erb
docs/geode-native-docs-dotnet/serialization/dotnet-serialization/serialize-using-ipdxserializable.html.md.erb
docs/geode-native-docs-dotnet/transactions.html.md.erb

Update method names to follow C# capitalization conventions.
Addresses occurrences enumerated in the JIRA ticket - not a comprehensive survey of the entire user guide.

GEODE-7282: Geode Native Client .NET guide: Fix capitalization issues

---

cppcache/integration/test/WanDeserializationTest.cpp

- Just want a green CI until GEODE-9634 is resolved.

GEODE-9637: Disable Wan deserialization test

---

ci/lib/templates.lib.txt
ci/release/pipeline.yml

* Provides an easy way to confirm the properties of the geode build used in the native-client tests
* Makes it easier to tell what build has passed all tests (since the current fan-in job has been paused since April)

Add a fan-in job and print out the properties of the Geode build used for test

---

netcore/asp-netcore-session-sample/asp-netcore-session-sample.csproj
netcore/netcore-integration-test/netcore-integration-test.csproj
netcore/netcore-lib/netcore-lib.csproj
netcore/netcore-session-integration-test/netcore-session-integration-test.csproj
netcore/netcore-session/netcore-session.csproj

The NetCore projects should be compiled with Warnings as Errors to be consistent with other geode-native components. Also, some of the projects are missing RelWithDebInfo configuration.
Remove Release config, add Optimization and pdb

GEODE-9608: NetCore projects should be compiled with Warnings as Error

---

cppcache/src/ThinClientRedundancyManager.cpp

- first endpoint in m_redundantEndpoints was originally supposed to
be left out of the for loop.  This broke during a refactor roughly three years ago, moving from old-school iterator to a ranged for loop.

GEODE-9848: Eliminate duplicate REGISTER_INTEREST message

---

dependencies/ACE/CMakeLists.txt

- fix building on macos monterry (which will make me happy)
Let me know if this should be  part of [GEODE-9896 Upgrade Dependencies](https://issues.apache.org/jira/projects/GEODE/issues/GEODE-9896?filter=allissues)
This may conflict with https://github.com/apache/geode-native/pull/899

GEODE-9896: Bump ace to 7.0.6

---

dependencies/sqlite/CMakeLists.txt

Seemed rude not to bump the other dependencies after doing ACE, so here is another one
May also conflict with #899
maybe some day I'll look into dependabot so this type of bumping can be automated

GEODE-9896: Bump sqlite to 3.37.2

---

dependencies/sqlite-netFx/CMakeLists.txt

last one for now as it seems like the other bumps I played with have bigger problems

GEODE-9896: bump sqlite-fx to 1.0.115.5

---

cppcache/src/ExpiryTask.hpp
cppcache/src/SerializationRegistry.cpp
cppcache/src/SerializationRegistry.hpp
tests/cpp/fwklib/CMakeLists.txt
tests/cpp/security/CMakeLists.txt
tests/cpp/security/CredentialGenerator.cpp
tests/cpp/security/CredentialGenerator.hpp
tests/cpp/security/DummyCredentialGenerator.cpp
tests/cpp/security/DummyCredentialGenerator2.cpp
tests/cpp/security/DummyCredentialGenerator2.hpp
tests/cpp/security/DummyCredentialGenerator3.cpp
tests/cpp/security/DummyCredentialGenerator3.hpp
tests/cpp/security/LdapUserCredentialGenerator.cpp
tests/cpp/security/LdapUserCredentialGenerator.hpp
tests/cpp/security/NoopCredentialGenerator.hpp
tests/cpp/security/PkcsCredentialGenerator.cpp
tests/cpp/security/PkcsCredentialGenerator.hpp
tests/cpp/testobject/DeltaTestImpl.cpp
tests/cpp/testobject/DeltaTestImpl.hpp

- Removed all ACE references from tests/cpp projects.
- In order to sort out incomplete types errors as a consecuence
of the changes above, inlined code from SerializationRegistry was
moved to the cpp file.

GEODE-9323: Remove ACE from tests/cpp projects

---

CMakeLists.txt
clicache/acceptance-test/CMakeLists.txt
clicache/integration-test/CMakeLists.txt
clicache/integration-test2/CMakeLists.txt
clicache/src/CMakeLists.txt
clicache/src/impl/AssemblyInfo.cpp.in
clicache/test2/CMakeLists.txt
templates/security/csharp/CMakeLists.txt
tests/cli/DUnitFramework/CMakeLists.txt
tests/cli/FwkClient/CMakeLists.txt
tests/cli/FwkLauncher/FwkLauncher.csproj.txt
tests/cli/FwkUtil/FwkUtil.csproj.txt
tests/cli/NewTestObject/CMakeLists.txt
tests/cli/PdxClassLibrary/CMakeLists.txt
tests/cli/PdxVersion1Lib/CMakeLists.txt
tests/cli/PdxVersion2Lib/CMakeLists.txt
tests/cli/QueryHelper/CMakeLists.txt
tests/cli/SecurityUtil/CMakeLists.txt

- This has caused problems with build pipelines, and is no longer used by .net runtimes

GEODE-9960: Remove strong name signing support for .net assemblies

---

docs/geode-native-docs-cpp/configuring/sysprops.html.md.erb
docs/geode-native-docs-dotnet/configuring/sysprops.html.md.erb

Simple deletion of a cross-reference from two source files, one for the C++ user guide, one for the .NET user guide.

GEODE-10030: Remove obsolete cross-reference in geode-native user docs

---

cppcache/src/ServerLocation.hpp
cppcache/src/ThinClientLocatorHelper.cpp

- Whenever there is an SSL missconfiguration while trying to reach a
locator, an AuthenticationRequiredException is thrown and a log is
written. Currently FQDN of the locator is not logged.
- This commit adds the locator FQDN in order to further troubleshoot
this kind of scenarios.
- Also, in order to ease implementation, toString method was
implemented for ServerLocation.

GEODE-9959: Add FQDN in log upon SSL missconfig

---

docs/geode-native-docs-cpp/getting-started/app-dev-walkthrough-cpp.html.md.erb
docs/geode-native-docs-cpp/getting-started/getting-started-nc-client.html.md.erb
docs/geode-native-docs-dotnet/getting-started/app-dev-walkthrough-dotnet.html.md.erb
docs/geode-native-docs-dotnet/getting-started/getting-started-nc-client.html.md.erb

Found four doc sources in the Getting Started section that were missing licenses.

Add license text to some doc sources

---

cppcache/integration/test/TransactionCleaningTest.cpp

- From time to time this test was failing with the error "Concurrent
modification in the cache". Thing is this test was not intended to
check concurrent modifications.
- In GEODE-9322 this test was modified to avoid a race-condition
whenever restarting the server. To do so, it was needed to enable
notification subscription and change the region shortcut to
CACHE_PROXY. In doing so, concurrent checks are also enabled, and due
to some strange race-condition this is occasionally leading to the exception.
- Concurrency checks were disabled for the region to avoid the
race-condition to happen at all

GEODE-10043: Solve TransactionCleaningTest failures

---

clicache/integration-test/CacheHelperN.cs

Occassionaly we see timeouts in the CI when running the legacy clicache tests. These appear to mostly be timeouts waiting for gfsh commands to complete.
The error message varies depending on what branch you're on:
- develop: "ExecuteGfsh: Timeout, killing 4604"
- 10.2.7: "Timed out waiting for Java cacheserver to stop"

GEODE-10040: Increase wait timeout for gfsh commands in the test framework

---

tools/gnmsg/handshake_decoder.py

- Hex dump of a pointer on Linux is prefixed with '0x', so need to
allow x or X character

GEODE-10074: Fix regex issue on Linux systems

---

cppcache/include/geode/CacheableEnum.hpp
cppcache/include/geode/internal/DSCode.hpp
cppcache/include/geode/internal/DSFixedId.hpp
cppcache/src/CacheableEnum.cpp
cppcache/src/ClientProxyMembershipID.cpp
cppcache/src/PdxInstanceImpl.cpp
cppcache/src/QueueConnectionRequest.cpp
cppcache/src/SerializationRegistry.cpp
cppcache/src/TXCommitMessage.cpp
cppcache/src/TcrConnection.cpp
cppcache/src/TcrMessage.cpp

Moves InterestResultPolicy and ClientProxyMembershipId to DSFid.
Replaces eroneous CacheableEnum with PDX_ENUM.

GEODE-10082: Fixes mixing of DSCode and DSFid enums.

---

clicache/integration-test2/Cluster.cs
cppcache/integration/framework/Cluster.cpp
cppcache/integration/framework/Cluster.h

This adds support for multiple locators in the new .NET test framework.

GEODE-10085: Don't start JmxManager if already running

---

tools/gnmsg/server_message_decoder.py

- These weren't correctly parsing since the addition of thread names to
log files
- Also had to make server message dumps regular dictionaries, because
OrderedDict has an issue with assignment to an existing field (?).

Fix regexes in server messages

---

.lgtm.yml
docker/centos-7/Dockerfile
docker/centos-8/Dockerfile
docker/rhel-7/Dockerfile
docker/rhel-8/Dockerfile
docker/ubuntu-16.04/Dockerfile
docker/ubuntu-18.04/Dockerfile
docker/ubuntu-20.04/Dockerfile
docker/windows/Dockerfile

Native client hardcodes Geode version to test with in several places.
Update those variables to latest-and-greatest apache-geode 1.14.4

GEODE-10101: Bump Geode version to 1.14.4

---

packer/build-windows-2016-vs-2017.json
packer/build-windows-2019-vs-2017.json
packer/build-windows-2019-vs-2019.json

This removes the comma left in the packer json file for the Windows images.

Remove spurious comma

---

cppcache/src/ClientMetadata.cpp

- On AppleClang 13.1.6.13160021, the warning -Wunused-but-set-variable
is appears as an error.  This allows compilation on AppleClang on
MacOS 12.3

GEODE-10131: Remove set but unused variables

---

docs/geode-native-book-dotnet/config.yml
docs/geode-native-docs-dotnet/about-client-users-guide.html.md.erb
docs/geode-native-docs-dotnet/client-cache-ref.html.md.erb
docs/geode-native-docs-dotnet/configuring/config-client-cache.html.md.erb
docs/geode-native-docs-dotnet/configuring/sysprops.html.md.erb
docs/geode-native-docs-dotnet/continuous-queries.html.md.erb
docs/geode-native-docs-dotnet/function-execution.html.md.erb
docs/geode-native-docs-dotnet/getting-started/app-dev-walkthrough-dotnet.html.md.erb
docs/geode-native-docs-dotnet/getting-started/getting-started-nc-client.html.md.erb
docs/geode-native-docs-dotnet/getting-started/put-get-example.html.md.erb
docs/geode-native-docs-dotnet/preserving-data/config-durable-reconnect.html.md.erb
docs/geode-native-docs-dotnet/preserving-data/using-queue-conflation.html.md.erb
docs/geode-native-docs-dotnet/regions/regions.html.md.erb
docs/geode-native-docs-dotnet/regions/registering-interest-for-entries.html.md.erb
docs/geode-native-docs-dotnet/remote-queries.html.md.erb
docs/geode-native-docs-dotnet/security/authentication.html.md.erb
docs/geode-native-docs-dotnet/serialization/data-serialization.html.md.erb
docs/geode-native-docs-dotnet/serialization/dotnet-serialization/dotnet-pdx-autoserializer.html.md.erb
docs/geode-native-docs-dotnet/serialization/dotnet-serialization/dotnet-pdx-serialization.html.md.erb
docs/geode-native-docs-dotnet/serialization/dotnet-serialization/pdx-serializable-examples.html.md.erb
docs/geode-native-docs-dotnet/serialization/dotnet-serialization/serialize-using-ipdxserializable.html.md.erb
docs/geode-native-docs-dotnet/transactions.html.md.erb

GEODE-9921: Update references of ".NET" to ".NET Framework" to clarify that we are not referring to .NET Core.

GEODE-9921: Rename .NET to .NET Framework

---

cppcache/src/TcrEndpoint.cpp

TcrEndpoint::sendRequestConn contains redundant calls to TcrConnection::sendRequestForChunkedResponse which should be removed.

GEODE-10227: Remove redundant sendRequestForChunkedResponse

---

docs/geode-native-docs-cpp/about-client-users-guide.html.md.erb
docs/geode-native-docs-cpp/client-cache-ref.html.md.erb
docs/geode-native-docs-cpp/continuous-queries.html.md.erb
docs/geode-native-docs-cpp/function-execution.html.md.erb
docs/geode-native-docs-cpp/serialization/cpp-serialization/pdxserializable-interface.html.md.erb

GEMNC-509: Rename .NET client to .NET Framework

---

clicache/integration-test2/Cluster.cs
clicache/integration-test2/Gfsh.cs
clicache/integration-test2/GfshTest.cs
cppcache/integration/framework/Cluster.cpp
cppcache/integration/framework/Cluster.h
cppcache/integration/framework/Gfsh.cpp
cppcache/integration/framework/Gfsh.h
cppcache/integration/test/AllowAttachTest.cpp
cppcache/integration/test/CMakeLists.txt

To assist with protocol analysis it is very helpful to be able to step through the server code in the Intellij debugger while running native client test code. However, to be allowed to set breakpoints in the server code, the server must be started with the special flag below:
```
--J=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=127.0.0.1:FREEPORT
```
This ticket is to add support for the above flag in the native client test frameworks.

GEODE-10218: Allow server debug

---

.lgtm.yml
docker/centos-7/Dockerfile
docker/centos-8/Dockerfile
docker/rhel-7/Dockerfile
docker/rhel-8/Dockerfile
docker/ubuntu-16.04/Dockerfile
docker/ubuntu-18.04/Dockerfile
docker/ubuntu-20.04/Dockerfile
docker/windows/Dockerfile

Native client hardcodes Geode version to test with in several places.
Update those variables to latest-and-greatest apache-geode 1.15.0

GEODE-10089: Bump Geode version to 1.15.0

---

cppcache/integration/test/PdxInstanceTest.cpp
tests/javaobject/CMakeLists.txt
tests/javaobject/ComparePdxInstanceFunction.java

- After merging #973, javaobject compilation was broken for Java 11.
The build passed since packer images uses Java 8, but as docker build
images uses Java 11, compilation is failing there.
- Root cause of the compilation issue is the difference in UTF-8 string
handling between Java 8 and Java 11.
- So, the issue was fixed by using unicode hexcode codepoint
characters, rather than the actual codepoint.

GEODE-10404: Fix javaobject compilation for Java 11

---

cppcache/integration/test/PdxTypeRegistryTest.cpp
cppcache/test/ConnectionQueueTest.cpp

Initially failed to compile because it could not find `sleep_for` (was undefined)

GEODE-10291: Compile on ubuntu jammy (gcc/g++ 11.2.0)

---

CMakeLists.txt

- Added a option in the CMake project to enable documentation generation.
- In order to maintain backward compatibility, by default documentation generation is enabled.

GEODE-10426: Add option to toggle doc generation
