apache/geode-native

- src/cppcache/include/gfcpp/CacheableDate.hpp
- src/cppcache/include/gfcpp/gfcpp_globals.hpp
- src/cppcache/src/CacheableDate.cpp
- src/tests/cpp/pdxautoserializerclass/AutoPdxVersioned1.cpp
- src/tests/cpp/pdxautoserializerclass/AutoPdxVersioned2.cpp
- src/tests/cpp/testobject/InvalidPdxUsage.hpp
- src/tests/cpp/testobject/NonPdxType.hpp
- src/tests/cpp/testobject/PdxAutoMegaType.cpp
- src/tests/cpp/testobject/PdxType.hpp
- src/tests/cpp/testobject/PdxTypeWithAuto.hpp
- src/tests/cpp/testobject/PdxVersioned1.cpp
- src/tests/cpp/testobject/PdxVersioned2.cpp
Moved from old repo to new repo. Can I get a thumbs up please?
> [GEODE-2408] Refactor CacheableDate with C++11 standards.

- docs/geode-native-docs/sqlite-persistence/chapter_overview.html.md.erb
- docs/geode-native-docs/sqlite-persistence/linux_install.html.md.erb
- docs/geode-native-docs/sqlite-persistence/solaris_install.html.md.erb
- docs/geode-native-docs/sqlite-persistence/windows_install.html.md.erb
Persistence Manager
@davebarnes97 @dgkimura @echobravopapa @mmartell @PivotalSarge @joeymcallister Please review these minimal changes to unbrand the documentation section called Installing the SQLite Persistence Manager.
> GEODE-2513 Unbrand docs section Installing the SQLite

- docs/geode-native-book/master_middleman/source/subnavs/geode-nc-nav.erb
- docs/geode-native-docs/transactions/how-native-client-xacts-work.html.md.erb
- docs/geode-native-docs/transactions/running-native-client-xact.html.md.erb
- docs/geode-native-docs/transactions/suspend-resume-xacts.html.md.erb
- docs/geode-native-docs/transactions/transactions.html.md.erb
- Also updated an instance of an old package namespace
@davebarnes97 @joeymcallister @dgkimura @mmartell @echobravopapa @PivotalSarge Please review this PR that updates the Transactions section of the documentation.
> GEODE-2513 Unbrand Transactions section of doc

- docs/geode-native-docs/function-execution/executing-functions.html.md.erb
- docs/geode-native-docs/function-execution/function-execution.html.md.erb
- docs/geode-native-docs/function-execution/handling-function-results.html.md.erb
- docs/geode-native-docs/function-execution/solutions-use-cases.html.md.erb
Very minor wording changes.
@davebarnes97 @joeymcallister, along with anyone else who cares to, please review.
> GEODE-2513 Unbrand Function Execution section of docs

- docs/geode-native-book/master_middleman/source/subnavs/geode-nc-nav.erb
- docs/geode-native-docs/about_native_client_users_guide.html.md.erb
- docs/geode-native-docs/cpp-caching-api/accessing-entry.html.md.erb
- docs/geode-native-docs/cpp-caching-api/add-entry-to-cache.html.md.erb
- docs/geode-native-docs/cpp-caching-api/cpp-caching-api.html.md.erb
- docs/geode-native-docs/cpp-caching-api/creating-cache.html.md.erb
- docs/geode-native-docs/cpp-caching-api/creating-new-statistics.html.md.erb
- docs/geode-native-docs/cpp-caching-api/creating-region.html.md.erb
- docs/geode-native-docs/cpp-caching-api/data-as-blob.html.md.erb
- docs/geode-native-docs/cpp-caching-api/gfe-cpp-api.html.md.erb
- docs/geode-native-docs/cpp-caching-api/object-graphs.html.md.erb
- docs/geode-native-docs/cpp-caching-api/pdx_auto_serialization.html.md.erb
- docs/geode-native-docs/cpp-caching-api/pdx_serialization.html.md.erb
- docs/geode-native-docs/cpp-caching-api/pdx_with_delta_propagation.html.md.erb
- docs/geode-native-docs/cpp-caching-api/pdxserializable_interface.html.md.erb
- docs/geode-native-docs/cpp-caching-api/removing-entry.html.md.erb
- docs/geode-native-docs/cpp-caching-api/serialization_options.html.md.erb
- docs/geode-native-docs/cpp-caching-api/serialization_overview.html.md.erb
- docs/geode-native-docs/cpp-caching-api/serialization_using_serializable.html.md.erb
- docs/geode-native-docs/cpp-caching-api/using-custom-class.html.md.erb
- docs/geode-native-docs/cpp-caching-api/using_enum_type_with_pdx.html.md.erb
- docs/geode-native-docs/cpp-caching-api/using_pdxinstancefactory.html.md.erb
Please review, paying the most attention to scoped class/function name changes.
@davebarnes97 @joeymcallister @PivotalSarge @echobravopapa @mmartell @dgkimura @mhansonP
> GEODE-2513 Unbrand C++ API docs

- docs/geode-native-book/master_middleman/source/subnavs/geode-nc-nav.erb
- docs/geode-native-docs/about_native_client_users_guide.html.md.erb
- docs/geode-native-docs/cache-init-file/chapter-overview.html.md.erb
- docs/geode-native-docs/client-cache/accessing-entries.html.md.erb
- docs/geode-native-docs/client-cache/adding-entries-to-cache.html.md.erb
- docs/geode-native-docs/client-cache/application-plugins.html.md.erb
- docs/geode-native-docs/client-cache/cache-management.html.md.erb
- docs/geode-native-docs/client-cache/cache-ownership.html.md.erb
- docs/geode-native-docs/client-cache/caches.html.md.erb
- docs/geode-native-docs/client-cache/caching-apis.html.md.erb
- docs/geode-native-docs/client-cache/chapter-overview.html.md.erb
- docs/geode-native-docs/client-cache/client-to-server-connection.html.md.erb
- docs/geode-native-docs/client-cache/closing-cache.html.md.erb
- docs/geode-native-docs/client-cache/consistency_checking_in_regions.html.md.erb
- docs/geode-native-docs/client-cache/create-access-cache.html.md.erb
- docs/geode-native-docs/client-cache/declarative-region-creation.html.md.erb
- docs/geode-native-docs/client-cache/getting-the-region-size.html.md.erb
- docs/geode-native-docs/client-cache/invalidating-region.html.md.erb
- docs/geode-native-docs/client-cache/managing-lifetime-cached-object.html.md.erb
- docs/geode-native-docs/client-cache/notification-for-operations.html.md.erb
- docs/geode-native-docs/client-cache/overview-client-cache.html.md.erb
- docs/geode-native-docs/client-cache/persistence-manager.html.md.erb
- docs/geode-native-docs/client-cache/region-shortcuts.html.md.erb
- docs/geode-native-docs/client-cache/registering-interest-for-entries.html.md.erb
- docs/geode-native-docs/client-cache/requirements-for-distrib.html.md.erb
- docs/geode-native-docs/client-cache/specify-region-attributes.html.md.erb
- docs/geode-native-docs/client-cache/troubleshooting.html.md.erb
- docs/geode-native-docs/client-cache/using-thread-safety.html.md.erb
- namespace updates
- fix typos
@davebarnes97 @joeymcallister @PivotalSarge @echobravopapa @dgkimura @mmartell @mhansonp
Please review, paying particular attention to the namespace changes.
> GEODE-2513 Unbrand docs section Configuring the Native Client Cache

- docs/geode-native-docs/continuous-querying/5b-writing-cq-listener.html.md.erb
- docs/geode-native-docs/delta-propagation/delta-propagation-api.html.md.erb
- docs/geode-native-docs/dotnet-caching-api/cpp-class-to-dotnet-class-mappings.html.md.erb
- docs/geode-native-docs/dotnet-caching-api/csharp-dotnet-naming-conventions.html.md.erb
- docs/geode-native-docs/dotnet-caching-api/data-serialization-apis.html.md.erb
- docs/geode-native-docs/dotnet-caching-api/dotnet-data-serialization-options.html.md.erb
- docs/geode-native-docs/dotnet-caching-api/dotnet-pdx-autoserializer.html.md.erb
- docs/geode-native-docs/dotnet-caching-api/primary-apis-cache-generic.html.md.erb
- docs/geode-native-docs/dotnet-caching-api/problem-scenarios.html.md.erb
- docs/geode-native-docs/function-execution/running-function.html.md.erb
- docs/geode-native-docs/programming-examples/serialization-csharp.html.md.erb
- docs/geode-native-docs/type_mappings/cpp-class-to-dotnet-class-mappings.html.md.erb
@davebarnes97 @joeymcallister @PivotalSarge @echobravopapa @dgkimura @mmartell 
I believe this PR changes all remaining instances of IGFSerializable in prose within the documentation.
> GEODE-2513 Docs: IGFSerializable becomes IGeodeSerializable

- tests/javaobject/GetFunctionExeHA.java
Fixes native client built against latest server sources.
https://issues.apache.org/jira/browse/GEODE-254
Testing: Linux built successfully.
> GEODE-3453: Fix native client function tests to use updated API

- cppcache/src/ThinClientRegion.cpp
- Changed some definitions to auto
- Removed some debug statements
- note: No shared_ptr change or loop change as they are not necessary. 
With regard to the "for" loop would not work, hence the while loop.
> GEODE-3741: removed debug statements and cleanup

- cppcache/include/geode/CacheableDate.hpp
- cppcache/src/CacheableDate.cpp
Test: built successfully on Windows
> GEODE-3605: Remove deprecated methods from public API

- clicache/src/AttributesFactory.cpp
- clicache/src/AttributesMutator.cpp
- clicache/src/CacheStatistics.cpp
- clicache/src/CacheStatistics.hpp
- clicache/src/CacheTransactionManager.cpp
- clicache/src/CqQuery.cpp
- clicache/src/Execution.cpp
- clicache/src/Pool.cpp
- clicache/src/PoolFactory.cpp
- clicache/src/Query.cpp
- clicache/src/Region.cpp
- clicache/src/RegionAttributes.cpp
- clicache/src/RegionFactory.cpp
- clicache/src/ResultCollector.cpp
- clicache/src/SystemProperties.cpp
- clicache/src/TimeUtils.hpp
- clicache/test/CMakeLists.txt
- clicache/test/TimeUtilsTests.cpp
- cppcache/include/geode/CacheStatistics.hpp
- cppcache/integration-test/CacheHelper.cpp
- cppcache/src/CacheStatistics.cpp
- cppcache/src/CacheTransactionManagerImpl.cpp
- cppcache/src/EntryExpiryHandler.cpp
- cppcache/src/EntryExpiryHandler.hpp
- cppcache/src/ExpiryTaskManager.cpp
- cppcache/src/ExpiryTaskManager.hpp
- cppcache/src/LocalRegion.cpp
- cppcache/src/MapEntry.hpp
- cppcache/src/RegionExpiryHandler.cpp
- cppcache/src/RegionExpiryHandler.hpp
- Convert .NET CacheStatistics to DateTime.
> GEODE-3392: Converts CacheStatistics to std::chrono.

- clicache/src/impl/CacheWriter.hpp
- clicache/src/impl/ManagedCacheWriter.cpp
-The extraneous change is causing a problem.
Pulling it to not block others.
> GEODE-3751: Removing an extraneous change

- clicache/src/Region.cpp
- clicache/src/Region.hpp
- clicache/src/impl/CacheLoader.hpp
- clicache/src/impl/ManagedCacheLoader.cpp
- clicache/src/impl/ManagedCacheLoader.hpp
- clicache/src/native_conditional_shared_ptr.hpp
- cppcache/include/geode/CacheListener.hpp
- cppcache/include/geode/CacheLoader.hpp
- cppcache/include/geode/CacheWriter.hpp
- cppcache/integration-test/TallyLoader.hpp
- cppcache/integration-test/ThinClientListenerInit.hpp
- cppcache/integration-test/ThinClientLocalCacheLoader.hpp
- cppcache/integration-test/testThinClientDisconnectionListioner.cpp
- cppcache/src/CacheListener.cpp
- cppcache/src/CacheLoader.cpp
- cppcache/src/CacheWriter.cpp
- cppcache/src/LocalRegion.cpp
Testing:
- Built on Windows
- Passed unit/integration tests on Windows
> GEODE-3991: Update callbacks to take region by reference

- BUILDING.md
Fixes to the BUILDING.md.
- Removed src from cmake command, and added GEODE_ROOT build option
- Added Apache Geode binaries to Required Tools section
> GEODE-4171: Putting in changes to fix and clarify the BUILDING.md

- BUILDING.md
There are more changes that were not included in the previous PR.
> GEODE-4171: Updating out-of-date content

- clicache/src/Cache.cpp
- clicache/src/PoolManager.cpp
- cppcache/include/geode/PoolFactory.hpp
- cppcache/include/geode/PoolManager.hpp
- cppcache/integration-test/CacheHelper.cpp
- cppcache/integration-test/CacheHelper.hpp
- cppcache/integration-test/ThinClientMultipleCaches.hpp
- cppcache/integration-test/testPoolFactory.cpp
- cppcache/integration-test/testThinClientAfterRegionLive.cpp
- cppcache/integration-test/testThinClientCqDurable.cpp
- cppcache/integration-test/testThinClientPoolAttrTest.cpp
- cppcache/integration-test/testThinClientSecurityMultiUserTest.cpp
- cppcache/src/CacheXmlParser.cpp
- cppcache/src/PoolFactory.cpp
- cppcache/src/PoolManager.cpp
- cppcache/src/PoolManagerImpl.cpp
- cppcache/src/PoolManagerImpl.hpp
- tests/cpp/fwklib/FrameworkTest.cpp
- tests/cpp/fwklib/FwkObjects.cpp
- tests/cpp/fwklib/FwkObjects.hpp
Testing: Unit/integration tests passed on Mac and Windows
> GEODE-4424: Refactor PoolManager::createFactory to return value

- clicache/src/PoolManager.cpp
- cppcache/include/geode/Cache.hpp
- cppcache/include/geode/Region.hpp
- cppcache/integration-test/ThinClientPutAll.hpp
- cppcache/integration-test/ThinClientPutAllWithCallBack.hpp
- cppcache/integration-test/testOverflowPutGetSqLite.cpp
- cppcache/src/LocalRegion.cpp
- cppcache/src/LocalRegion.hpp
- cppcache/src/ProxyRegion.hpp
Testing: Unit/integration tests passed on Mac and Windows
> GEODE-4412: Remove std::enable_shared_from_this from Cache hierarchy

- examples/cpp/customserializable/Order.cpp
- examples/cpp/customserializable/Order.hpp
- examples/cpp/customserializable/main.cpp
- examples/cpp/customserializer/main.cpp
- examples/cpp/put-get-remove/main.cpp
Fix examples that broke due to this refactor.
> GEODE-4424: Fix broken examples

- clicache/src/CacheableBuiltins.hpp
- cppcache/include/geode/CacheableBuiltins.hpp
- cppcache/include/geode/Pool.hpp
- cppcache/integration-test/BuiltinCacheableWrappers.hpp
- cppcache/integration-test/testRegionTemplateArgs.cpp
- cppcache/integration-test/testThinClientBigValue.cpp
- cppcache/integration-test/testThinClientCacheableStringArray.cpp
- cppcache/integration-test/testThinClientCacheablesLimits.cpp
- cppcache/integration-test/testThinClientClearRegion.cpp
- cppcache/integration-test/testThinClientContainsKeyOnServer.cpp
- cppcache/integration-test/testThinClientCqDelta.cpp
- cppcache/src/BucketServerLocation.hpp
- cppcache/src/DiffieHellman.cpp
- cppcache/src/PdxInstanceFactoryImpl.cpp
- cppcache/src/PdxInstanceImpl.cpp
- cppcache/src/TcrConnection.cpp
- cppcache/src/TcrConnection.hpp
- cppcache/src/TcrMessage.cpp
- cppcache/src/TcrMessage.hpp
- cppcache/src/ThinClientPoolDM.cpp
- cppcache/src/VersionedCacheableObjectPartList.cpp
- templates/security/PkcsAuthInit.cpp
- tests/cpp/security/PkcsAuthInit.cpp
- tests/cpp/security/Security.cpp
- tests/cpp/testobject/ArrayOfByte.hpp
- tests/cpp/testobject/BatchObject.cpp
- tests/cpp/testobject/DeltaTestImpl.cpp
- tests/cpp/testobject/TestObject1.cpp
- tests/cpp/testobject/TestObject1.hpp
Testing: Unit/integration tests passed on Windows
> GEODE-4449: Replace Cacheable array macro-templates with plain template

- cppcache/integration-test/CacheHelper.cpp
- cppcache/integration-test/CacheHelper.hpp
- pass PoolFactory by reference
- improve readability by converting to C++11
> GEODE-4688: Refactor the addServerLocatorEPs

- CONTRIBUTING.md
- Fixes formatting and code block highlights.
> Updates contributing instructions with refactoring guides.

- cppcache/include/geode/CacheableBuiltins.hpp
- cppcache/include/geode/internal/CacheableKeys.hpp
- cppcache/src/CacheableDate.cpp
- cppcache/src/PdxSerializable.cpp
- cppcache/src/PdxWrapper.cpp
- cppcache/test/CacheableKeysTest.cpp
Signed-off-by: Echo Bravo <eburghardt@pivotal.io>
> GEODE-4408: Move CacheableKeys.hpp to internal include dir

- cppcache/include/geode/DataInput.hpp
- cppcache/src/DataInput.cpp
- cppcache/src/TcrMessage.cpp
- cppcache/src/TcrMessage.hpp
- cppcache/src/util/JavaModifiedUtf8.hpp
- cppcache/test/util/JavaModifiedUtf8Tests.cpp
Signed-off-by: Blake Bender <bbender@pivotal.io>
> GEODE-4381: Refactoring readCacheableString() decoding

- packer/windows/install-dependencies.ps1
Signed-off-by: Ryan McMahon <rmcmahon@pivotal.io>
> GEODE-4799: Adding nuget to packer

- clicache/integration-test/CacheHelperN.cs
- clicache/integration-test/ThinClientPoolTestsN.cs
- clicache/integration-test/ThinClientQueryTestsN.cs
- clicache/integration-test/ThinClientRemoteQueryExclusivenessTests.cs
- clicache/src/PoolFactory.cpp
- clicache/src/PoolFactory.hpp
- examples/dotnet/AuthInitialize/Program.cs
- examples/dotnet/PdxAutoSerializer/Program.cs
- examples/dotnet/PutGetRemove/Program.cs
- tests/cli/NewFwkLib/FwkTest.cs
Cleanup and replace PR 277 to fix merge problem.
> GEODE-4842: Rebase with develop

- packer/dev-windows-2012-r2.json
- packer/windows/install-dependencies-app-from-github.ps1
https://github.com/lucasg/Dependencies/releases
> GEODE-5093: Installing Dependencies app on Windows dev image

- clicache/src/SystemProperties.hpp
- cppcache/include/geode/SystemProperties.hpp
Simple corrections identified [paired with @mmartell] back in May that weren't included in the May check-in.
> GEODE-4728: api docs - fix SystemProperties docs

- packer/windows/install-dependencies.ps1
Signed-off-by: Ivan Godwin <igodwin@pivotal.io>
> cmake install switched to 'latest'

- clicache/integration-test/ThinClientDeltaTestFailing.cs
Hi there, 
I wrote this bot based on the top 10 most misspelled english words.
(https://blog.oxforddictionaries.com/2016/08/02/corpus-misspellings/)
The bot queries, forks, clones, fixes and commits but I manually create the PRs.
All the best,
Jimmy
> Fixed Spelling.

- docs/geode-native-book/master_middleman/source/subnavs/geode-nc-nav.erb
- docs/geode-native-docs/about-client-users-guide.html.md.erb
- docs/geode-native-docs/client-cache/registering-interest-for-entries.html.md.erb
- docs/geode-native-docs/continuous-querying/continuous-queries.html.md.erb
- docs/geode-native-docs/getting-started/getting-started-nc-client.html.md.erb
Basic framework to be augmented with an example.
> GEODE-5648: Native client user guide - add a Continuous Query page 

- docs/geode-native-docs/configuring/configuration.html.md.erb
- docs/geode-native-docs/getting-started/getting-started-nc-client.html.md.erb
Emphasized connection pool of locators, incorporated code from existing C++ and C# put-get-remove examples.
> GEODE-5672: Geode Native Docs: explain how to connect apps to the server

- examples/dotnet/CMakeLists.txt
- examples/dotnet/CMakeLists.txt.in
- examples/dotnet/ContinuousQueryCs/MyCqListener.cs
- examples/dotnet/ContinuousQueryCs/Order.cs
- examples/dotnet/ContinuousQueryCs/Program.cs
- examples/dotnet/ContinuousQueryCs/README.md
- examples/dotnet/ContinuousQueryCs/startserver.ps1
- examples/dotnet/ContinuousQueryCs/stopserver.ps1
- examples/dotnet/PdxSerializableCs/README.md
- examples/dotnet/RemoteQueryCs/README.md
- Also fix up README files for PdxSerializableCs and RemoteQueryCs
> GEODE-4347: Add dotnet ContinuousQuery example

- clicache/integration-test2/GeodeServer.cs
Allows these tests to be run in parallel. Also reformats the source file.
> Fix cli integration-test2 flakiness

- clicache/integration-test2/CMakeLists.txt
- clicache/integration-test2/CqOperationTest.cs
- clicache/integration-test2/GeodeServer.cs
- clicache/src/CqOperation.hpp
- cppcache/include/geode/CqOperation.hpp
- cppcache/src/Task.hpp
- cppcache/src/TcrChunkedContext.hpp
- Also fix issue with CQ and AppDomains
> GEODE-5750: Fix incorrect optype enum value

- clicache/integration-test2/CMakeLists.txt
- clicache/integration-test2/CqOperationTest.cs
- clicache/integration-test2/GeodeServer.cs
- clicache/integration-test2/GeodeServerTests.cs
- clicache/integration-test2/Position.cs
- clicache/integration-test2/server.xml
- clicache/integration-test2/xunit.runner.json
- tests/javaobject/CMakeLists.txt
- tests/javaobject/Position.java
- tests/javaobject/cli/Position.java
> GEODE-5768: New ContinuousQuery tests using DataSerializable objects

- cppcache/src/CacheImpl.cpp
- cppcache/src/CacheImpl.hpp
- cppcache/test/CMakeLists.txt
- cppcache/test/CacheTest.cpp
> GEODE-5898: Throw CacheClosedException after Cache is closed.

- clicache/integration-test/cache.xml
- clicache/integration-test/cache_redundancy.xml
- clicache/integration-test/client_Loader.xml
- clicache/integration-test/client_generics_plugins.xml
- clicache/integration-test/client_pdx.xml
- clicache/integration-test/client_pool.xml
- clicache/integration-test/invalid_cache1.xml
- clicache/integration-test/invalid_cache2.xml
- clicache/integration-test/invalid_cache3.xml
- clicache/integration-test/invalid_cache_pool.xml
- clicache/integration-test/invalid_cache_pool2.xml
- clicache/integration-test/invalid_cache_pool3.xml
- clicache/integration-test/invalid_cache_pool4.xml
- clicache/integration-test/invalid_overflowAttr1.xml
- clicache/integration-test/invalid_overflowAttr2.xml
- clicache/integration-test/invalid_overflowAttr3.xml
- clicache/integration-test/valid_cache.xml
- clicache/integration-test/valid_cache_refid.xml
- clicache/integration-test/valid_cache_region_refid.xml
- clicache/integration-test/valid_declarative_cache_creation.xml
- clicache/integration-test/valid_lruExpiration.xml
- clicache/integration-test/valid_overflowAttr.xml
- clicache/integration-test2/cache.xml
- cppcache/test/CacheXmlParserTest.cpp
Co-authored-by: Ernest Burghardt <eburghardt@pivotal.io>
> GEODE-2610: Fix up schema links in all references in source tree

- clicache/src/IDataSerializable.hpp
- clicache/src/TypeRegistry.hpp
- cppcache/include/geode/AuthenticatedView.hpp
- cppcache/include/geode/CacheTransactionManager.hpp
- cppcache/include/geode/CacheableEnum.hpp
- cppcache/include/geode/CacheableFileName.hpp
- cppcache/include/geode/CacheableObjectArray.hpp
- cppcache/include/geode/CacheableUndefined.hpp
- cppcache/include/geode/DataSerializable.hpp
- cppcache/include/geode/Delta.hpp
- cppcache/include/geode/EntryEvent.hpp
- cppcache/include/geode/PdxSerializable.hpp
- cppcache/include/geode/Serializable.hpp
- cppcache/include/geode/TypeRegistry.hpp
- adding missing class comments
- fixed class comments that were in the wrong place
> GEODE-5919: Fix documentation bugs

- cppcache/integration-test-2/CMakeLists.txt
- cppcache/integration-test-2/FunctionExecutionTest.cpp
- cppcache/src/ExecutionImpl.cpp
- cppcache/src/TcrMessage.cpp
- cppcache/src/TcrMessage.hpp
- All are just essentially string error messages
- Provides more detail about what happened on server
> GEODE-5957: Parse (previously) unknown server error messages

- cppcache/include/geode/Exception.hpp
Signed-off-by: Matthew Reddington <mreddington@pivotal.io>
> GEODE-6245: Fix Microsoft pragma warnings

- clicache/integration-test2/CMakeLists.txt
- clicache/integration-test2/CacheXmlTests.cs
- clicache/integration-test2/Cluster.cs
- clicache/integration-test2/ClusterTest.cs
- clicache/integration-test2/CqOperationTest.cs
- clicache/integration-test2/Framework.cs
- clicache/integration-test2/FunctionExecutionTest.cs
- clicache/integration-test2/Gfsh.cs
- clicache/integration-test2/GfshExecute.cs
- clicache/integration-test2/GfshExecuteTest.cs
- clicache/integration-test2/GfshTest.cs
- clicache/integration-test2/QueryTest.cs
- clicache/integration-test2/RegionSSLTest.cs
- clicache/integration-test2/RegionTest.cs
- clicache/integration-test2/SerializationTests.cs
- clicache/integration-test2/TestBase.cs
- tests/cli/PdxClassLibrary/PdxType.cs
- tests/cli/PdxClassLibrary/PdxTypesReflectionTest.cs
- Changes Gfsh wrapper:
- to be more stateless.
- use more explicit 1:1 mappings to actaual GFSH tool.
- Changes Cluster to keep more state previously held by Gfsh.
- Add support for XUnit's test output facility.
> GEODE-6241: Makes .NET integration tests more consistent with C++

- CMakeLists.txt
- cppcache/CMakeLists.txt
- cppcache/integration-test/CacheHelper.cpp
- cppcache/integration-test/CacheHelper.hpp
- cppcache/src/CacheTransactionManagerImpl.cpp
- cppcache/src/ExecutionImpl.cpp
- cppcache/src/ExpiryTaskManager.cpp
- cppcache/src/ExpiryTaskManager.hpp
- cppcache/src/InternalCacheTransactionManager2PCImpl.cpp
- cppcache/src/LocalRegion.cpp
- cppcache/src/LocalRegion.hpp
- cppcache/src/PdxTypeRegistry.cpp
- cppcache/src/TSSTXStateWrapper.cpp
- cppcache/src/TSSTXStateWrapper.hpp
- cppcache/src/TXCleaner.cpp
- cppcache/src/TXCleaner.hpp
- cppcache/src/TcrMessage.cpp
- cppcache/src/ThinClientPoolDM.cpp
- cppcache/src/ThinClientPoolStickyDM.cpp
- cppcache/src/ThinClientRegion.cpp
- cppcache/src/TransactionSuspender.cpp
- cppcache/src/TransactionSuspender.hpp
- cppcache/static/CMakeLists.txt
- cryptoimpl/CMakeLists.txt
- dependencies/boost/CMakeLists.txt
Adds some stability to old C++ integration tests.
Replaces a little more ACE.
Cleanup up IPO/WPO integration with CMake.
>  GEODE-2484: Remove more ACE and cleanup

- clicache/src/Cache.hpp
- clicache/src/PoolFactory.hpp
- cppcache/include/geode/Pool.hpp
- cppcache/include/geode/PoolFactory.hpp
- cppcache/include/geode/SystemProperties.hpp
- cppcache/src/InternalCacheTransactionManager2PCImpl.cpp
Co-authored-by: Dave Barnes <dbarnes@pivotal.io>
> GEODE-6623: Corrected typos and language

- cppcache/include/geode/ExceptionTypes.hpp
- cppcache/include/geode/PoolFactory.hpp
- cryptoimpl/SSLImpl.cpp
Co-authored-by: Ivan Godwin <igodwin@pivotal.io>
Co-authored-by: Jake Barrett <jbarrett@pivotal.io>
> GEODE-3415: Fix SSL certificate chain support

- cppcache/src/ThinClientPoolDM.cpp
Improvements in cleanStaleConnections method:
- introduce phasing
- return connections to pool as soon as possible
> GEODE-6576: Improvements in cleanStaleConnections method

- dependencies/ACE/CMakeLists.txt
- dependencies/benchmark/CMakeLists.txt
- dependencies/sqlite/CMakeLists.txt
* ACE 6.5.5
* google/benchmark 1.5.0
* SQLite 3.28.0
> GEODE-6840: Upgrade third party dependencies

- xsds/cpp-cache-1.10-DRAFT.xsd
Work in progress - took this as far as I was able, soliciting input.
> GEODE-6795: Update and correct Native Client XSD

- cppcache/benchmark/CMakeLists.txt
- cppcache/benchmark/GeodeLoggingBM.cpp
- cppcache/src/CacheXmlParser.cpp
Measure logging to file and logging to console for several different sized strings, ints, and a combination of the two.
@steve-sienk
> GEODE-6957: Add simple logging benchmarks

- cppcache/integration/framework/Cluster.cpp
- cppcache/integration/framework/Cluster.h
- cppcache/integration/framework/Gfsh.h
- cppcache/integration/test/BasicIPv6Test.cpp
- cppcache/integration/test/CMakeLists.txt
- cppcache/src/ClientProxyMembershipID.cpp
- cppcache/src/ClientProxyMembershipID.hpp
- cppcache/src/ClientProxyMembershipIDFactory.cpp
- cppcache/src/ClientProxyMembershipIDFactory.hpp
- cppcache/src/PoolFactory.cpp
- cppcache/src/ServerLocation.hpp
- cppcache/src/TcpConn.cpp
- cppcache/src/TcrConnection.cpp
- cppcache/src/ThinClientPoolDM.cpp
- cppcache/src/statistics/HostStatSampler.cpp
- cppcache/test/ClientProxyMembershipIDFactoryTest.cpp
- cppcache/test/ClientProxyMembershipIDTest.cpp
- dependencies/ACE/config.h.in
These are modifications in geode-native driver to run it on IPv6 environment.
> GEODE-7086: coding impacts for support of IPv6

- BUILDING.md
Updated the build instructions for mac after watching a new person to the project attempt to build the project.
> Update the build instructions for Mac

- packer/windows/install-openssl.ps1
- reflects update on OpenSSL site
> GEODE-7225: Change download URL from 'c' to 'd'

- examples/cpp/transaction/README.md
- examples/dotnet/transaction/README.md
Fine-tuning the explanation of example output. Applying parallel edits to both C++ and .NET versions.
> GEODE-7203: Update transaction example README files

- examples/cpp/continuousquery/startserver.ps1
- examples/cpp/dataserializable/startserver.ps1
- examples/cpp/pdxserializable/startserver.ps1
- examples/cpp/pdxserializer/startserver.ps1
- examples/cpp/transaction/stopserver.ps1
- server scripts using wrong region name
> GEODE-7285: Fix examples on Windows

- cppcache/include/geode/internal/geode_base.hpp
- cppcache/src/TcrConnection.hpp
- cppcache/src/ThinClientPoolDM.cpp
- cppcache/src/ThinClientPoolDM.hpp
- cppcache/src/util/exception.hpp
LGTM pointed out a few things, tried to fix them.  Also cleaned up some thing CLion pointed out to me.  Hopefully this doesn't add new things to LGTM
Will make a jira later if this turns out alright, this was mostly stuff I could easily pick up/put down while waiting for some other builds
> Some cleanup in ThinClientPoolDM

- cppcache/integration/test/CMakeLists.txt
- cppcache/integration/test/CqPlusAuthInitializeTest.cpp
- cppcache/integration/test/CqTest.cpp
- cppcache/integration/test/SimpleCqListener.cpp
- cppcache/integration/test/SimpleCqListener.hpp
- dependencies/boost/CMakeLists.txt
* Replace counters with latch.
> GEODE-7528: Fixes race condition in tests.

- cppcache/src/ClientProxyMembershipID.cpp
- cppcache/src/ClientProxyMembershipID.hpp
-apply some clang tidy messages
> GEODE-7549: Fix LGTM - Remove empty conditional

- cppcache/src/CacheImpl.cpp
- cppcache/src/CacheImpl.hpp
- cppcache/src/CppCacheLibrary.cpp
- cppcache/src/CppCacheLibrary.hpp
- cppcache/src/CqQueryVsdStats.cpp
- cppcache/src/CqQueryVsdStats.hpp
- cppcache/src/CqServiceVsdStats.cpp
- cppcache/src/CqServiceVsdStats.hpp
- cppcache/src/MapSegment.cpp
- cppcache/src/MapSegment.hpp
- cppcache/src/PoolStatistics.cpp
- cppcache/src/PoolStatistics.hpp
- cppcache/src/RegionStats.cpp
- cppcache/src/SerializationRegistry.cpp
- cppcache/src/TcrEndpoint.hpp
- cppcache/src/ThinClientPoolDM.hpp
- cppcache/src/ThinClientRedundancyManager.hpp
- cppcache/src/statistics/HostStatSampler.cpp
- cppcache/src/statistics/HostStatSampler.hpp
- cppcache/src/statistics/StatArchiveWriter.cpp
> GEODE-2484: Removes more ACE mutex.

- clicache/integration-test2/AutoSerializationTests.cs
- clicache/integration-test2/CMakeLists.txt
- clicache/src/ReflectionBasedAutoSerializer.cpp
- clicache/src/ReflectionBasedAutoSerializer.hpp
- clicache/src/TypeRegistry.cpp
- clicache/src/impl/DotNetTypes.hpp
Enhances the ReflectionBasedAutoSerializer to support unsigned types, Guids, and Decimals. There are no new APIs, only additions to the autoserializer.
New AutorSerializer tests have been added to the new test framework for .NET.
> GEODE-7868: Enhance ReflectionBasedAutoSerializer

- clicache/src/CMakeLists.txt
- cppcache/shared/CMakeLists.txt
- cryptoimpl/CMakeLists.txt
- Valid for Debug and RelWithDebInfo configs
@vfordpivotal @mreddington @davebarnes97 @dihardman @karensmolermiller
> GEODE-8015: Install PDB (symbol) files on Windows builds

- dependencies/ACE/CMakeLists.txt
- dependencies/sqlite/CMakeLists.txt
- dependencies/xerces-c/CMakeLists.txt
* ACE 6.5.8
* SQLite 3.31.1
* Xerces-C 3.2.3
> GEODE-7990: Updates dependencies

- dependencies/ACE/CMakeLists.txt
- dependencies/boost/CMakeLists.txt
Update to ACE 6.5.9
Update to Boost 1.73.0
> GEODE-8080: Updates dependencies.

- cppcache/integration/test/CMakeLists.txt
- cppcache/integration/test/ServerDisconnectWithListener.cpp
This test was designed to assist with debugging of issues discovered with boost::asio.
> GEODE-8214: Add new ServerDisconnect test

- cppcache/integration-test/fw_dunit.cpp
- cppcache/integration-test/fw_dunit.hpp
- cppcache/integration-test/testDunit.cpp
- cppcache/src/ExecutionImpl.cpp
- tests/cli/NewFwkLib/Utils.cs
master/slave --> primary/secondary
@mreddington @dihardman @davebarnes97 @karensmolermiller @moleske
> GEODE-8262: Replace insensitive terms in dunit framework

- cppcache/integration-test/ThinClientPutGetAll.hpp
- cppcache/src/ClientProxyMembershipIDFactory.cpp
We acquired a couple new compiler warnings in the upgrade, so this placates the Mac build for XCode 12.
> GOEDO-8534: fix xcode 12 build

- cppcache/include/geode/StringPrefixPartitionResolver.hpp
- cppcache/src/StringPrefixPartitionResolver.cpp
- cppcache/test/CMakeLists.txt
- cppcache/test/StringPrefixPartitionResolverTest.cpp
- Added StringPrefixPartitionResolver as it is included on the Java API
- UTs were added to verify the PR functionality.
> GEODE-8702: Add StringPrefixPartitionResolver

- tools/gnmsg/client_message_decoder.py
- tools/gnmsg/client_messages.py
- tools/gnmsg/command_line.py
- tools/gnmsg/gnmsg.py
- tools/gnmsg/server_message_decoder.py
- filter messages by thread, so we can see which responses correspond to
which requests
- also decoded the CONTAINS_KEY message in the course of other debugging
> GEODE-8868: Add thread_id parameter to gnmsg command line

- tools/gnmsg/numeric_conversion.py
- tools/gnmsg/read_values.py
- tools/gnmsg/server_messages.py
> GEODE-8902: parse server destroy reply in gnmsg

- cppcache/src/CacheImpl.cpp
- cppcache/src/ClientProxyMembershipID.cpp
- cppcache/src/ClientProxyMembershipID.hpp
- cppcache/src/TcrConnection.cpp
- cppcache/src/ThinClientLocatorHelper.cpp
- cppcache/src/Version.cpp
- cppcache/src/Version.hpp
- Support multibyte version.
- Use current gossip version.
> GEODE-8837: Announce correct version on handshake.

- clicache/integration-test2/PositionKey.cs
- clicache/src/CMakeLists.txt
- clicache/src/CacheableDate.cpp
- clicache/src/Objects.cpp
- clicache/src/Objects.hpp
- clicache/test2/CMakeLists.txt
- clicache/test2/ObjectsTests.cs
- tests/javaobject/cli/PositionKey.java
* Adds Objects util similar to Java's Objects util.
* Adds test to validate consistency with Java.
> GEODE-8910: Corrects hashing between .NET and Java

- BUILDING.md
- CONTRIBUTING.md
- README.md
* Updates established versioning rules.
* Fixes links to CI badge.
* Fixes links to internal anchors.
* Fixes links to logo.
* Updates OS versions.
* Updates tooling versions.
* Moves contributing details from BUILDING.md to CONTRIBUTING.md.
> Updates README.md, CONTRIBUTING.md and BUILDING.md

- cppcache/integration/test/RegisterKeysTest.cpp
- Sometimes it could happen that in RegisterAllWithConsistencyDisabled
test the call to afterDestroy happens before the expectance is set.
THis leads to the test sporiously failing.
- Expect call has been moved after the listener instantiation to avoid
this race condition.
> GEODE-9026: Fix RegisterKeysTest race condition

- cppcache/integration/test/RegisterKeysTest.cpp
- As it seems there is still a very rare race condition that might
cause the test to fail.
- If the listener is called before wait_for is called, the test fails
due to timeout.
- A flag and predicate has been added to tackle this race condition.
> GEODE-9026: Fix race cond in RegisterKeysTest #2

- tools/gnmsg/client_messages.py
- tools/gnmsg/read_parts.py
- tools/gnmsg/server_messages.py
Also move some shareable routines into a shared area, and a couple of small refactors like alphabetizing a list etc
> GEODE-9054: Parse ADD_PDX_TYPE message from client

- docs/geode-native-docs-cpp/configuring/config-client-cache.html.md.erb
- docs/geode-native-docs-dotnet/configuring/config-client-cache.html.md.erb
Tweak to previous -- fix 2 links
> GEODE-6816: geode-native userguide: fix broken api links

- docs/geode-native-book-cpp/config.yml
- docs/geode-native-book-cpp/redirects.rb
- docs/geode-native-book-dotnet/config.yml
- docs/geode-native-book-dotnet/redirects.rb
> Docs: update develop version to 1.15

- tools/gnmsg/client_message_decoder.py
- tools/gnmsg/server_message_decoder.py
- printf output for "%p" appears to have changed, need to accomodate this
@mreddington
> GEODE-9154: gnmsg accepts hex format for pointers, as well as decimal

- dependencies/rat/CMakeLists.txt
- docker/centos-7/Dockerfile
- docker/centos-8/Dockerfile
- docker/rhel-7/Dockerfile
- docker/rhel-8/Dockerfile
- docker/ubuntu-16.04/Dockerfile
- docker/ubuntu-18.04/Dockerfile
- docker/windows/Dockerfile
Apache removed the filename parameter from the closer.cgi.
https://issues.apache.org/jira/browse/INFRA-21767
> Replace deprecated Apache closer.cgi with closer.lua.

- cppcache/include/geode/CqQuery.hpp
> GEODE-9364 - Fixed spelling mistake in Api documentation.

- .asf.yaml
(cherry picked from commit 26367260daaa114c78efba87c1349f13cf2dadd1)
> Re-enable .asf.yaml checks that the release-merge removed. (thanks, Git)

- tools/gnmsg/chunked_message_decoder.py
- tools/gnmsg/client_message_decoder.py
- tools/gnmsg/server_message_decoder.py
- makes the tool robust against weird versions of NC
- no longer any need to combine rolled log files to parse messages
Also fixed several issues I noticed in timestamps:
- chunked server responses didn't have timestamps
- some timestamps were strings, others datetime objects, so they printed out differently ('/' vs '-')
- gnmsg wasn't parsing out the date, only the timestamp, so output had today's date rather than the date in the log file
@todmorrison
> GEODE-9387: Ignore version trace in gnmsg

- tools/gnmsg/client_message_decoder.py
- tools/gnmsg/server_message_decoder.py
- Compiling regex every time we check a line for matches is silly, made
the regexes member variables of the decoder classes and only compile
them once.
- Short-circuited regex checking by doing a "sanity check" using a
substring search for each line before using regex.  Substring search
is much, much cheaper than re.search().
Performance comparison follows.  I ran gnmsg on two log files, one "normal" and one that was extremely slow to scan.
Results for the normal file: 7.434 seconds dropped to 0.786 seconds (9.4x faster), relevant function calls shown below:
```
Before:
2258846 function calls (2219404 primitive calls) in 7.434 seconds
Ordered by: standard name
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
22117    0.009    0.000    0.216    0.000 …
```
> Performance improvements for gnmsg script

- tools/gnmsg/server_message_decoder.py
- Chunked messages can come in on multiple threads simultaneously, and
gnmsg only had one decoder.  If two message headers came in on
different threads prior to the message body arriving for the first
thread, gnsmg would get confused and think it had received two headers
without a body, throwing an exception.  Now we keep a chunk decoder
per thread, and things run much more smoothly.
> gnmsg - Fix chunked decoding in some log files

- cppcache/integration-test/testThinClientPdxTests.cpp
- cppcache/src/RegionAttributes.cpp
Our Ubuntu Docker image picked up a new version of the tools yesterday, so we need to reformat a couple of files.
> Fix formatting

- .asf.yaml
- ci/lib/templates.lib.txt
Need to fix some infrastructure issues without going through days of process.
> (Temporarily) Unlock develop

- BUILDING.md
- CMakeLists.txt
- CONTRIBUTING.md
- ci/base/base.yml
- cmake/CXXFlags.cmake
* Adds checks for some sanitizer options.
* Adds options to enable sanitizers.
* Extracts checks for LTO.
* Adds options to disable LTO.
> Disables LTO on RHEL-8

- tools/gnmsg/chunked_message_decoder.py
- tools/gnmsg/client_message_decoder.py
- tools/gnmsg/client_messages.py
- tools/gnmsg/gnmsg.py
- tools/gnmsg/interest_policy.py
- tools/gnmsg/interest_type.py
- tools/gnmsg/server_message_decoder.py
- also, only print a summary of chunked messages, since these can get insanely large
- add a minor perf tweak to regular expressions
> gnmsg - decode REGISTER_INTEREST message

- packer/build-rhel-8.json
Looks like a typo to me. This should disable background updates on rhel8.
> Fix to disable auto updates on rhel8

- cppcache/src/FunctionMacros.hpp
- cppcache/src/ThinClientLocatorHelper.cpp
- tools/gnmsg/client_messages.py
- tools/gnmsg/ds_fids.py
- tools/gnmsg/gnmsg.py
- tools/gnmsg/handshake_decoder.py
- tools/gnmsg/modified_utf8.py
- tools/gnmsg/read_values.py
- Dump the bytes at debug log level, so we can parse
- Also added parsing of these to gnmsg tool
> GEODE-10073: Print bytes of ClientConnectionRequest/Response in logs

- docs/geode-native-docs-cpp/client-cache-ref.html.md.erb
- docs/geode-native-docs-cpp/configuring/sysprops.html.md.erb
- docs/geode-native-docs-cpp/getting-started/app-dev-walkthrough-cpp.html.md.erb
- docs/geode-native-docs-dotnet/client-cache-ref.html.md.erb
- docs/geode-native-docs-dotnet/configuring/sysprops.html.md.erb
- docs/geode-native-docs-dotnet/getting-started/app-dev-walkthrough-dotnet.html.md.erb
> GEODE-10062: Update Native Client Docs - additions and corrections

- cppcache/src/TcrConnection.cpp
- cppcache/src/TcrConnection.hpp
- tools/gnmsg/client_message_decoder.py
- tools/gnmsg/gnmsg.py
- tools/gnmsg/handshake_acceptance_codes.py
- tools/gnmsg/handshake_decoder.py
- tools/gnmsg/read_values.py
- tools/gnmsg/server_message_decoder.py
- Also clean up TcrConnection::initTcrConnection for clarity
- Also rename TcrConnection member variables to conform to coding standards
> Gnmsg parse server handshake response

- .lgtm.yml
- related to the earlier ubuntu break, so applying the same fix
> Fix lgtm ubuntu break

- docs/geode-native-book-dotnet/config.yml
- docs/geode-native-docs-dotnet/about-client-users-guide.html.md.erb
- docs/geode-native-docs-dotnet/client-cache-ref.html.md.erb
- docs/geode-native-docs-dotnet/configuring/config-client-cache.html.md.erb
- docs/geode-native-docs-dotnet/configuring/sysprops.html.md.erb
- docs/geode-native-docs-dotnet/continuous-queries.html.md.erb
- docs/geode-native-docs-dotnet/function-execution.html.md.erb
- docs/geode-native-docs-dotnet/getting-started/app-dev-walkthrough-dotnet.html.md.erb
- docs/geode-native-docs-dotnet/getting-started/getting-started-nc-client.html.md.erb
- docs/geode-native-docs-dotnet/getting-started/put-get-example.html.md.erb
- docs/geode-native-docs-dotnet/preserving-data/config-durable-reconnect.html.md.erb
- docs/geode-native-docs-dotnet/preserving-data/using-queue-conflation.html.md.erb
- docs/geode-native-docs-dotnet/regions/regions.html.md.erb
- docs/geode-native-docs-dotnet/regions/registering-interest-for-entries.html.md.erb
- docs/geode-native-docs-dotnet/remote-queries.html.md.erb
- docs/geode-native-docs-dotnet/security/authentication.html.md.erb
- docs/geode-native-docs-dotnet/serialization/data-serialization.html.md.erb
- docs/geode-native-docs-dotnet/serialization/dotnet-serialization/dotnet-pdx-autoserializer.html.md.erb
- docs/geode-native-docs-dotnet/serialization/dotnet-serialization/dotnet-pdx-serialization.html.md.erb
- docs/geode-native-docs-dotnet/serialization/dotnet-serialization/pdx-serializable-examples.html.md.erb
- docs/geode-native-docs-dotnet/serialization/dotnet-serialization/serialize-using-ipdxserializable.html.md.erb
- docs/geode-native-docs-dotnet/transactions.html.md.erb
Porting https://github.com/apache/geode-native/pull/960 to other versions
> GEODE-9921: Rename .NET to .NET Framework

- ci/lib/templates.lib.txt
- cppcache/src/TcrMessage.cpp
Add echo command to cmake configuration step, for debugging
> GEODE-10382: Fix Windows build in CI pipeline
